/*
* Copyright 2010, Andrew M Gibson
*
* www.andygibson.net
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
* http://www.apache.org/licenses/LICENSE-2.0
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

package org.jdataset.testing;

import java.util.Calendar;
import java.util.Date;
import java.util.Random;

/**
 * Class that provides a number of methods for generating test data.
 * 
 * @author Andy Gibson
 *
 */
public final class TestDataFactory {

	private static Random random = new Random();

	private static String[] suffixes = { "II", "III", "Phd", "Jr", "Sr" };
	private static String[] prefixes = { "Mr", "Mrs", "Ms" };
	private static String[] firstNames = { 
		"JAMES","JOHN","MICHAEL","ROBERT","DAVID","JENNIFER","WILLIAM",
		"MARY","CHARLES","RICHARD","ASHLEY","JASON","JESSICA","JOSHUA","BRIAN",
		"MIKE","LISA","HEATHER","AMANDA","JUSTIN","JEFF","MICHELLE","TAMMY",
		"LINDA","MELISSA","AMY","MARK","JOSEPH","STEPHANIE","SCOTT","CHRIS",
		"TERRY","AMBER","DONALD","KELLY","GARY","MATTHEW","ANGELA","PAUL",
		"KEVIN","LARRY","THOMAS","CHAD","BRANDON","SHAWN","BRENDA","REBECCA",
		"ANTHONY","KATHY","BRITTANY","KIMBERLY","MISTY","JEREMY","DEBBIE","RANDY",
		"TINA","DANIEL","RYAN","STEVE","ERIC","CHRISTINA","TIFFANY","KAREN",
		"CRYSTAL","SUSAN","BARBARA","STEVEN","DEBRA","KYLE","TIMOTHY","TYLER",
		"TIM","SAMANTHA","JAMIE","TERESA","SARAH","RONALD","AUSTIN","JIM",
		"ELIZABETH","BILL","JERRY","ANDREW","KENNETH","AARON","APRIL","CINDY",
		"ROGER","DUSTIN","JULIE","KAYLA","JACOB","PATRICIA","CODY","NICOLE",
		"KEITH","SHANNON","LORI","ROBIN","RICK","DONNA","TOM","GEORGE",
		"KIM","JOE","CHERYL","RAYMOND","CAROL","ADAM","CHRISTOPH","MEGAN",
		"SHERRY","SHARON","CONNIE","DANNY","JACK","DIANE","JEFFREY","NANCY",
		"BETTY","SHANE","CHRISTOPHER","LAURA","CHRISTINE","TODD","JUDY","NICHOLAS",
		"NATHAN","TRACY","RHONDA","DALE","RUSSELL","FRANK","CATHY","COURTNEY",
		"STACY","THERESA","TRAVIS","BILLY","TONYA","DAN","JESSE","STACEY",
		"SHIRLEY","JORDAN","BECKY","BEVERLY","BRYAN","CARRIE","PAMELA","WENDY",
		"BOB","KENNY","RACHEL","RON","SANDRA","PAM","EMILY","ANDREA",
		"SARA","HEIDI","HAROLD","GREG","DANIELLE","BETH","ANGEL","CAROLYN",
		"COREY","TROY","CARL","HOLLY","JACKIE","JONATHAN","JOSH","JIMMY",
		"ERICA","ANGIE","DAKOTA","SANDY","PHILLIP","PEGGY","PAULA","DON",
		"DESTINY","BRAD","JOEY","BRANDY","CRAIG","CASSANDRA","DAVE","DEBORAH",
		"JAMES","JOHN","MICHAEL","ROBERT","DAVID","JENNIFER","WILLIAM",
		"MARY","CHARLES","RICHARD","ASHLEY","JASON","JESSICA","JOSHUA","BRIAN",
		"MIKE","LISA","HEATHER","AMANDA","JUSTIN","JEFF","MICHELLE","TAMMY",
		"LINDA","MELISSA","AMY","MARK","JOSEPH","STEPHANIE","SCOTT","CHRIS",
		"TERRY","AMBER","DONALD","KELLY","GARY","MATTHEW","ANGELA","PAUL",
		"KEVIN","LARRY","THOMAS","CHAD","BRANDON","SHAWN","BRENDA","REBECCA",
		"ANTHONY","KATHY","BRITTANY","KIMBERLY","MISTY","JEREMY","DEBBIE","RANDY",
		"TINA","DANIEL","RYAN","STEVE","ERIC","CHRISTINA","TIFFANY","KAREN",
		"CRYSTAL","SUSAN","BARBARA","STEVEN","DEBRA","KYLE","TIMOTHY","TYLER",
		"TIM","SAMANTHA","JAMIE","TERESA","SARAH","RONALD","AUSTIN","JIM",
		"ELIZABETH","BILL","JERRY","ANDREW","KENNETH","AARON","APRIL","CINDY",
		"ROGER","DUSTIN","JULIE","KAYLA","JACOB","PATRICIA","CODY","NICOLE",
		"KEITH","SHANNON","LORI","ROBIN","RICK","DONNA","TOM","GEORGE",
		"KIM","JOE","CHERYL","RAYMOND","CAROL","ADAM","CHRISTOPH","MEGAN",
		"SHERRY","SHARON","CONNIE","DANNY","JACK","DIANE","JEFFREY","NANCY",
		"BETTY","SHANE","CHRISTOPHER","LAURA","CHRISTINE","TODD","JUDY","NICHOLAS",
		"NATHAN","TRACY","RHONDA","DALE","RUSSELL","FRANK","CATHY","COURTNEY",
		"STACY","THERESA","TRAVIS","BILLY","TONYA","DAN","JESSE","STACEY",
		"SHIRLEY","JORDAN","BECKY","BEVERLY","BRYAN","CARRIE","PAMELA","WENDY",
		"BOB","KENNY","RACHEL","RON","SANDRA","PAM","EMILY","ANDREA",
		"SARA","HEIDI","HAROLD","GREG","DANIELLE","BETH","ANGEL","CAROLYN",
		"COREY","TROY","CARL","HOLLY","JACKIE","JONATHAN","JOSH","JIMMY",
		"ERICA","ANGIE","DAKOTA","SANDY","PHILLIP","PEGGY","PAULA","DON",
		"DESTINY","BRAD","JOEY","BRANDY","CRAIG","CASSANDRA","DAVE","DEBORAH",
		
		"EDWARD","DOUG","ANNA","TONY","ZACHARY","RALPH","JANET","BRADLEY",
		"ALEXIS","ALISHA","VIRGINIA","VALERIE","RODNEY","MARGARET","FRED","DAWN",
		"ANN","BOBBY","JODY","JONATHON","JENNY","VICTORIA","BONNIE","DOROTHY",
		"MATT","PATRICK","SUE","RUTH","MELINDA","MANDY","ALEX","GERALD",
		"STEPHEN","ROY","PATTY","HARRY","DENNIS","DENISE","CYNTHIA","CORY",
		"CARLA","PENNY","VICKI","TAYLOR","TARA","ROSE","RAY","MARILYN",
		"MADISON","HANNAH","JAY","KATIE","JEFFERY","CHASE","ANDY","SHELLY",
		"PAT","JOYCE","CHRISTIAN","BRENT","BARB","KRISTEN","RENEE","SHAWNA",
		"WAYNE","MARSHA","LYNN","JESSIE","EARL","VICKIE","WESLEY","VICKY",
		"SHEILA","RITA","KENDRA","ERIN","ALBERT","RICKY","NATASHA","JANICE",
		"DARLENE","BOBBIE","AUTUMN","MELANIE","SEAN","TAMARA","SAM","PAIGE",
		"MORGAN","LESLIE","GLORIA","DIANA","ALLEN","BILLIE","TOMMY","MARTHA",
		"GREGORY","DEREK","CASEY","CANDY","CAMERON","BRANDI","BRUCE","HELEN",
		"VICTOR","TRISHA","TRACEY","TERRI","TABITHA","SABRINA","MONICA","MITCHELL",
		"KRISTA","DOUGLAS","CHRISTY","ANITA","BENJAMIN","LEONARD","MINDY","SAMUEL",
		"SALLY","RUSTY","ROCKY","MIRANDA","LINDSAY","KRISTINA","JOHNNY","ED",
		"ALLISON","ALYSSA","BROOKE","MOTHER","MARCUS","JASMINE","FAITH","ETHAN",
		"DANA","CLARENCE","CALEB","ARTHUR","CATHERINE","BLAKE","CHELSEA","WALTER",
		"TIMMY","SETH","RANDALL","LORETTA","JODI","HOWARD","HALEY","ALICE",
		"BRIANNA","BRETT","KEN","LEROY","TED","RONNIE","REX","REGINA",
		"NOAH","NICK","MOLLY","MARIA","LLOYD","WANDA","VANESSA","LAWRENCE",
		"KAYLEE","JENNA","EVA","DEVIN","CHUCK","ALAN","ALICIA","SHAUN",
		"LAKEN","KYLIE","KATHRYN","JOANN","JEREMIAH","HUNTER","GINA","FATHER",
		"SIERRA","DARREN","COLTON","ANNETTE","CHARLENE","BROOKLYN","CHARLIE",
		"DERRICK","STANLEY","MARVIN","MARIE","LOGAN","LINDSEY","JEANNIE",
		"JEAN","FRANCIS","DYLAN","CHASITY","BRADY","DARLA","DARRELL","EVELYN",
		"GLEN","LEVI","KRISTY","KRISTIN","KATRINA","KATHERINE","JULIA","JON",
		"JAN","HARLEY","WHITNEY","ROBBIE","LOUIS","LOIS","GENE","FLOYD",
		"DOMINIC","DILLON","DEANNA","CHARLOTTE","BREANNA","ABBY","NORMAN","MARY ANN",
		"LEE","JARED","JANE","HOPE","GRACE","GINGER","GAIL","TRENT",
		"TESSA","SUMMER","ELAINE","DONNIE","DEAN","CLAYTON","CLARA","ABIGAIL",
		"BETHANY","DUSTY","VINCENT","VERNON","TIA","TASHA","SKYLER","SHANDA",
		"SAVANNAH","ROCHELLE","PHYLLIS","MARLENE","LACEY","KELSEY","KATHLEEN","KAITLYN",
		"JOEL","ISAAC","HERBERT","ERIKA","ELLEN","LEAH","EDDIE","CLIFFORD",
		"CLINT","CHESTER","ALEXANDRA","ALISSA","WILLIE","UNBORN",
		"TREVOR","NORMA","MYRON","MICKEY","MELODY","MAX","MASON","MARTIN",
		"MARIAH","LANCE","SYDNEY","SHERRI","ROXANNE","KRIS","KATELYN","JOANNE",
		"JILL","JAKE","GAGE","EVERETT","EUGENE","LEWIS","ERNEST","DUANE",
		"DREW","DIXIE","DALLAS","CURTIS","CHEYENNE","CARMEN","CHASTITY","DORIS",
		"DALTON","GABRIEL","HEATH","JADE","JUANITA","TASHIA","TABATHA",
		"RONDA","ROBERTA","ROB","RANDI","RACHAEL","PETE","OLIVIA","NINA",
		"MARTY","MARION","KAY","VERONICA","TYRONE","TRISTAN","TONI","JOHNATHAN",
		"IAN","GLENN","FELICIA","ANTONIO","AUDREY","BABY","WYATT",
		"VIVIAN","TREY","TRACIE","THELMA","SHERYL","SHANNA","RUSS","ROD",
 };

	private static String[] lastNames = { 
		"SMITH","MILLER","JOHNSON","BROWN","DAVIS","WILLIAMS","MOORE","MAYLE","TAYLOR",
		"HARRIS","HILL","WILSON","JONES","EVANS","NORRIS","WHITE","CLARK","ROBERTS",
		"MORGAN","ROBINSON","THOMAS","SCOTT","MARTIN","CAMPBELL","GIBSON","ANDERSON","THOMPSON",
		"CURTIS","HALL","ADAMS","WHEELER","GRANT","NEWELL","WEST","HAYES","JACKSON",
		"ALEXANDER","YOUNG","WOOD","GOINS","PLETCHER","MURPHY","COLLINS","LEWIS","ALLEN",
		"JENKINS","STEWART","ROSS","BAILEY","DENNIS","REED","KING","TABLER","KENNEDY",
		"GILL","SIMS","MITCHELL","BAKER","BARNETT","STEVENS","MORRIS","HAMILTON","DUNN",
		"HARPER","FOWLER","JAMES","NORMAN","BEACH","WICKHAM","STOTTS","SHAW","SHARRER",
		"ROSE","NEWMAN","FORD","NELSON","FOSTER","CLAPPER","HALE","MCDONALD","CAPLINGER",
		"WISECARVER","MYERS","COOPER","CARTER","GREEN","KIRKBRIDE","WALKER","MCGEE","SNYDER",
		"WEBB","EDWARDS","BROOKS","MORRISON","WRIGHT","FISHER","TRACEY","MAXWELL","BENNETT",
		"BURNS","WELLS","WARD","WAGNER","VALENTINE","SOWERS","SIMPSON","FERRELL","CARROLL",
		"DEVOLL","RILEY","DOBBINS","STARKEY","TURNER","TATE","HUNTER","CRAWFORD","CUNNINGHAM",
		"WOLFE","GHEEN","MCCORMICK","HENDERSON","DRAKE","BARKER","RUTTER","ROGERS","MOODY",
		"MCHENRY","GROSS","DUNLAP","CORDER","NEWTON","RUSSELL","WADE","BELL","HAMPTON",
		"HUGHES","HOPPER","KIMBLE","WINLAND","TANNER","SAVAGE","POWELL","PHILLIPS","MASON",
		"CHANDLER","DICKINSON","BRYANT","LARIMER","PRIDE","WATTS","SPENCER","PRICE","MERCER",
		"LEE","KELLY","HUNT","DUNKLE","SUTTLES","SWINGLE","MOHLER","BARR","RUSH",
		"PERRY","HASTINGS","FRANK","CHAPMAN","ARNOLD","DEBOLT","FLEMING","BUTLER","BATES",
		"GRIMES","TUCKER","STARCHER","REYNOLDS","RAY","MARSHALL","HUFFMAN","GARDNER","BAGLEY",
		"BUTCHER","COLEMAN","KESSLER","PALMER","WINTERS","WEAVER","TODD","STEMM","RICE",
		"PITTS","PIERCE","MATTHEWS","LENTZ","HENRY","HARVEY","DOOLEY","COTTRELL","CARPENTER",
		"BRENNAN","WILLIAMSON","SCHNEIDER","SANDERS","PARKER","NEFF","LOWE","HARTMAN","DOYLE",
		"CARNES","BRYAN","BUNTING","BROWNING","BOWEN","CHURCH","DILLON","HOOD","HOLLAND",
		"HITTLE","HARTER","GLOSSER","FOX","FERGUSON","DODSON","MULLINS","DALTON","COCHRAN",
		"BREWER","ELLIOTT","WALLACE","TYO","MCELFRESH","CRAMER","COEN","BASH","BOYD",
		"WOODS","WISE","UNTIED","SPEARS","SAXTON","PAYNTER","MCNUTT","LANE","JOSEPH",
		"JEWELL","HUTCHINSON","HOWARD","HEWITT","HARROP","HARRIMAN","HARLAN","GORDON","FRANCIS",
		"DANIEL","CURRY","BRANDON","BARNES","DRAUGHN","MCCLELLAND","PATTERSON","TOUVELL","WATSON",
		"VAN DYNE","SWOPE","MILLS","JORDAN","BESSER","BOWERS","DANIELS","ASHTON","WILLETT",
		"WATKINS","UNK","SPRING","SAMSON","ORE","NUTTER","NICHOLSON","MCWHORTER","MAHON",
		"MADINGER","GAMBLE","FREEMAN","BENDER","COX","DAILEY","ARCHER","HUTTON","LANDERMAN",
		"WILLEY","TOM","TIPTON","SEEVERS","REESE","PARMER","MCPHERSON","LASHLEY","LAMB",
		"HILES","BUSH","DIXON","GRAY","GRAHAM","DINGEY","ANGLER","WYATT","WORK",
		"TIGNOR","SWARTZ","SHEPPARD","SHEPHERD","SHAFER","SEALEY","PORTER","OWENS","MONTGOMERY",
		"MAULLER","LOVEJOY","LITTLE","LANNING","KUHN","KNOX","KINNEY","GILLOGLY","FRAZIER",
		"FIELDS","DERWACTER","CHURCHILL","CHAPPELEAR","BOWMAN","BOBB","BLEVINS","HINA","HATFIELD",
		"GRANDSTAFF","BERRY","BALL","CHAMBERS","HIXON","LIGHTFOOT","TROUT","SHUMATE","ROMINE",
		"RIVERA","RIGGS","PARRISH","MOYER","MIRACLE","LINSCOTT","WARNER","HUDSON","HINKLE",
		"HAMMER","BARNHART","BRUCE","CARR","BISHOP","BALDWIN","YOCUM","WORDEN","WELCH",
		"VANDYNE","SHAFFER","PROUTY","NORTHRUP","NICHOLS","MCLEAN","MCKEE","MCFARLAND","MCBRIDE",
		"MARPLE","LONG","GOLDSMITH","GALIGHER","FARMER","ECHELBERRY","DENNEY","COOK","CARSEY",
		"CANNON","BURKE","HIGGINS","HARRIER","HANNING","BLACK","BOGGS","BOLLINGER","BRIGHT",
		"BONIFIELD","BOCOOK","ABBOTT","BICE","MURRAY","MOCK","MINGUS","MELVIN","MCDANIEL",
		"LYNN","GILMORE","GEE","GARRETT","FRENCH","FRANKLIN","FITZPATRICK","EWERT","EDDY",
		"DUSENBERRY","PECK","NORTON","LAYTON","KIRBY","KERN","JUSTICE","HOWDYSHELL","HAWKINS",
		"GRAVES","VAUGHN","UNDERWOOD","RYAN","RICHARDS","QUINN","CORBIN","CONKLE","COLBURN",
		"CALDWELL","BICKFORD","BENSON","ABELE","BECKETT","MICK","MCCANDLESS","LYONS","LUCKETT",
		"LUCAS","LECKRONE","HUFF","HOLMES","HOLBERT","HOFFMAN","HENNESSY","HARDY","GOHRING",
		"GLASS","GEORGE","SPENCE","SNIDER","SIDWELL","RUCKER","ROUSH","RIDER","RALPH",
		"POTTS","PAYNE","WISEMAN","WILLS","WILKINS","WARREN","WALTERS","TRAVIS","TEMPLE",
		"SUMMERVILLE","STOTTSBERRY","GAMBILL","FORAKER","ELDRIDGE","EFAW","DUFF","DRABIK","CRONIN",
		"CORNELL","CORBETT","CLAYPOOL","BRADLEY","BORING","BIRD","ARBUCKLE","BARRY","BAUSERMAN",
		"WHITEHOUSE","VINCENT","STERLING","STEELE","STARNER","SNODGRASS","SNELL","SHERWOOD","SCHULTZ",
		"ROYER","ROWAN","RANSOM","RAMSEY","POLLOCK","PITTMAN","PEYTON","PETERSON","PARSONS",
		"NETHERS","MUMAW","MOZENA","MOOREHEAD","MCMANNIS","MCMANES","MCCUTCHEON","MCCOID","MCCLINTOCK",
		"MCCLELLAN","MCCARTY","MAURER","MASSEY","MARTINDALE","LUMAN","LOPEZ","LEHMAN","KIRKPATRICK",
		"KINDER","KEMP","JAMISON","HESKETT","HAVENS","HARDWICK","HANSON","GUY","GRETHER",
		"FRAME","FLUHARTY","FESLER","FANNIN","ESTEP","EPPLEY","ELSON","ELLERS","EDGELL",
		"DUNAWAY","DOUGLAS","DILTS","DILLY","DEVLIN","DAYTON","CONRAD","CLIFFORD","CHILDERS",
		"BARNHOUSE","AGIN","BACK","BECK","DALRYMPLE","ZIEGLER","WOLFORD","WOFTER","WICKER",
		"WENTWORTH","WARNE","WALTZ","VINEY","STEVENSON","SNACK","SHROYER","SHORT","SARBAUGH",
		"REGER","ESTRADA","ERVIN","DURST","DRIGGS","DONALDSON","DILLEY","DICKERSON","DENNY",
		"DEITENBECK","RADER","PIEPER","PEPPER","OSBORNE","OLNEY","MILATOVICH","MEEK","MCGILTON",
		"MCFEE","MCCONNELL","MAY","MALONE","MALLERNEE","LYNCH","LOVE","KNIGHT","KNAPP",
		"JOHNSTON","JASPER","JARVIS","JARRETT","IRVIN","HOSTUTLER","HORTON","HOOK","HOLLINS",
		"HOLLINGSHEAD","HOLDREN","HICKMAN","HERNANDEZ","HARNEY","HARMON","HARDING","GOODRICH","GIBBS",
		"GARD","FLOWERS","FLICKINGER","CLINE","BURGESS","CAMP","BRADSHAW","BATROSS","ABRAM",
		"ADKINS","ALWINE","ECKERTSON","DYER","DUNCAN","DULING","DOBSON","DEVOL","CONLEY",
		"COHEN","CAMPFIELD","CALE","BURKHART","BRYSLAN","BRONKAR","BRISTER","BRILL","WEINSTOCK",
		"WAKELEY","VEYON","UPHOLD","TRUSSELL","TRACY","TOWNING","TILTON","STIRES","STEED",
		"SPINKS","SPELLMAN","SPANGLER","SMYTHE","SMYERS","SLEVIN","SIMON","SHUMAKER","SHRYOCK",
		"SEYMOUR","SAUNDERS","RUPE","ROCKWELL","RITTENHOUSE","RHOADES","RAMOS","PRINCE","POULTON",
		"POTTER","PINKERTON","PEDDICORD","PAISLEY","NOVARIA","NOEL","NICHOLAS","NEWSOM","NASH",
		"MORAN","MICKENS","METCALF","MCCOY","LIGGETT","LEASURE","LANG","KRAMER","KOEHNLE",
		"KNOWLDEN","KLINEHOFFER","JENNINGS","ISRAEL","HUBER","HANCOCK","HAMMONDS","GRABLE","GILLESPIE",
		"GETTER","FULLER","FOUST","FELL","FELDNER","HARTLEY","HARRISON","ENGLE","EMORY",
		"DECKER","DAY","DAWSON","DALE","CULLINS","CORNELIUS","GRUBBS","GRIFFIN","GREINER",
		"BOYER","BOYCE","BEATTY","BEALE","ASHCRAFT","ARMSTRONG","ANKROM","ATKINSON","ELLIS",
		"EHRNFIELD","ECLEBERY","DUNWOODY","DRUMHELLER","DOZER","DICKS","DIAMOND","DAUGHERTY","DARR",
		"YARGER","WOLF","WILLIS","WHYDE","WHITSON","WESTERHEIDE","VANCE","URBAN","TYSON",
		"TOLBERT","TERRILL","TALBERT","SUTTON","STILLION","STAUFFER","STARR","SPIRES","SIX",
		"SIMMONS","SHOEMAKER","SHEPHARD","SANDS","RUTHERFORD","ROWLAND","RODGERS","ROACH","RAU",
		"PYLE","PULLIE","PRESTON","SEVERT","SCHMIDT","POLING","PERP","PAYTON","PAUL",
		"OSBORN","OLDEN","NULL","NEAL","MOUNT","MICHAEL","MESSNER","MCKINLEY","MCGRAW",
		"MCGLADE","MARKS","MALLETT","NEWLAND","LOVINGSHIMER","LESTER","LAWRENCE","LANTZ","LAMBERT",
		"KREPS","KRAUSE","KENNEY","KELSO","KELLER","HUGHETT","HOLSMAN","HODGE","HIETT",
		"HEAD","GREGG","GIFFEN","GEBHART","FUNK","FRYE","FRY","FRAUNFELTER","FELUMLEE",
		"FARR","GRUBB","CRUMP","CROSTON","COVERT","CHANEY","CAREINS","BUZZA","BURKETT",
		"BROCK","DEGARMO","BOOKLESS","BISSETT","BAUER","BARTLETT","AULT","BAILES","ANDREWS",
		"AYERS","YESTER","YERIAN","WION","WESTCOTT","WAHL","VAN ALLEN","TULLIUS","SZOKE",
		"SULLIVAN","STUCHELL","STROCK","STORIE","STOLFTUZ","ST. CLAIR","SMITHSON","SMART","SMALL",
		"SINDELDECKER","SILVA","SHULTZ","SHEETS","SHATTO","SEXTON","SEATON","SCHWARTZ","SCHEFFLER",
		"ROLLISON","ROLLINS","ROESSLER","RENICK","RAMBO","PRITCHARD","PICKENPAUGH","PETTRY","PERRIN",
		"PAXSON","PARRILL","OLIVER","OFFINGER","NOLL","MUNYAN","MONSEWICZ","MOBLEY","MILNER",
		"MICHEL","MEDLEY","MCFADDEN","MCELROY","MATLOCK","MATHIAS","MATHENEY","MARSH","MANLET",
		"MANGUS","MANGOLD","MANEELY","LUTGEN","LOGAN","LOCKE","LEVINGSTON","LETT","LESLIE",
		"LAYNE","LARRICK","LAKE","LAGRANGE","KLEIN","KENT","KANE","JAZDZEWSKI","JADWIN",
		"JACOBS","HUMPHREY","HOWE","HINDEL","HICKS","HEATH","HARRY","HARGRAVES","HARDAWAY",
		"GURNICKE","GRUNDY","GRIMM","GONZALEZ","GODFREY","GLOVER","GIFFIN","GIBBONS","GATES",
		"GARNES","GARNER","GARBER","FRALEY","FRACKER","FLOOD","FLEECE","FITCH","FINK",
		"FILKILL","EUMAN","EUBANKS","DECHERD","DEAN","DARBY","DAILY","CUSICK","CROZIER",
		"CROSBY","CROM","CASH","ELMORE","EICKLEBERRY","ECLEBERRY","DURANT","DUMOLT","DUDAS",
		"CAMERON","CALLAHAN","BURRELL","BUNDY","BULLOCK","BOOHER","BOGARD","BLACKETTER","DEAL",
		"CONAWAY","COLLIER","COLES","COLBORN","CHRISTIAN","CECIL","CAVALEAR","CATON","BENTLEY",
		"BEISSER","BEEBE","BAY","BARCUS","ACHAUER","ARGO","BICKLE","HELLINGER","HEARLD",
		"HEAGREN","HEADLEY","HAYHURST","HASTEN","HARMER","HARLEY","HANNUM","ZINK","YINGLING",
		"YATES","WYER","WORSTALL","WEATHERSPOON","WAZENSKI","WAUGAMAN","WADLINGTON","VICKERS","VEST",
		"VANDENBARK","VAN HORN","TYLER","SNURR","SINGER","SIMMS","SHEARER","SELLERS","SEALY",
		"SEALS","SCURLOCK","SCHRACK","SCHOOLEY","SANDBRINK","SALYERS","RUSHING","RUBY","ROGNAN",
		"RIMEL","RIEHL","RANSON","PUTERBAUGH","PURDUE","PRATT","POWERS","PLUMMER","PHIPPS",
		"PEYATT","PETTIFORD","PERKINS","PERDUE","PAXTON","PARKS","PAGE","OLTMAN","OGLE",
		"O'NEILL","NOLAND","NIGMAN","NEELY","NAYLOR","NASON","MIDDLEBROOK","MEREDITH","MEFFORD",
		"MCQUAIN","MCPECK","MCNERNEY","MCMULLEN","MCKOWN","MCINTIRE","MCCALL","MASUKU","MANN",
		"MALLORY","MAKIN","LYALL","LUBY","LOWERY","LOWERS","LONGSDORF","LINDER","LICHTNER",
		"LEMLEY","LEIBY","LEAR","LEACH","LAWVER","LANDIS","KOENIG","KNIPE","KILDOW",
		"KELLEY","KEGLEY","JUDSON","ISCH","TOWNSEND","TIDD","TATMAN","TAGGART","TABOR",
		"SWANSON","STYERS","STONEROOK","STONE","STINES","STEPHENS","SOWARDS","INSLEY","HUMMEL",
		"HRINKO","HOY","HOOPER","HOLSKEY","HOADLEY","HILLIS","HAMMERSLEY","HAHN","HADLEY",
		"GOUGH","GOODNITE","GOODMAN","GIFFORD","GAUSE","HAREN","HARDESTY","GARRISON","GAITERS",
		"GAISER","FRITZ","FRITCH","FOUCH","FORTNEY","FLYNN","FLEMMING","FARRELL","EVELAND",
		"EPLER","ENGLISH","ENGLES","EMRICK","DOMORACKI","DEVORE","DAVIDSON","DADY","CROCK",
		"CREECH","CRAVENOR","BROOKER","BRAY","ELKINS","DUPLER","DUNFEE","DONAHOE","BRANDOM",
		"BRAGLIN","BOTTOMLEY","BOOKOUT","BOLYARD","BLAND","BLACKFORD","BIRKHIMER","DENMAN","COLYER",
		"CHAMBLIN","CAW","CARDER","CANTRELL","CALVERT","BURROUGHS","BUCKLEY","BENJAMIN","ADOLPH",
		"BARTIMUS","BANKS","BALLARD","ATKINS","ANDERS","ADAIR","YURICH","YOST","YOCKEY",
		"YAGER","WOOLEY","WOERNER","WINSLEY","WINEGAR","WIMER","WILCOX","WHETSTONE","WEISER",
		"WEIDIG","WEEKLEY","WEBER","WAXLER","WARE","WALTON","VARNER","VANWEY","VANDERHOFF",
		"ULLMAN","TUDOR","TRIPLETT","TRIANA","TOBIAS","TIPPIE","THORPE","THOMSEN","TEMPLETON",
		"TARMAN","SWINEY","SWEENEY","STURGILL","STRIBLIN","STONER","STONEBURNER","STOLTZFUS","STIGALL",
		"STEIL","STARLIN","STANLEY","STANFORD","STALNAKER","SPILLMAN","SPARKS","SPARGROVE","SPANG",
		"SNOW","SLATER","SLACK","SHIPMAN","SHIPLEY","SHELL","SHAHAN","SHACKLEFORD","SEWARD",
		"SCOLES","SCHOTTS","SCHOOP","SARVEY","SALMONS","RUSNAK","RUBALCABA","ROZNOWSKI","ROTH",
		"ROBISON","ROBBINS","ROBB","ROADES","RIPLEY","RINE","RIFFLE","RIEDER","RICHARD",
		"RICH","REDFERN","REAVLEY","RANDLES","PICKENS","PHILLIS","PFEIFER","PENNINGTON","PAULUS",
		"PARRETT","PARK","PAINE","OUTLAND","ORWIG","OILER","O'NEAL","NICKELL","NEECE",
		"NAVARRO","MYAL","MOUSER","MORTON","MOON","MESSER","MERIDETH","MCNIGHT","MCNEMAR",
		"MCLAUGHLIN","MCGUIRE","MCCOLLUM","MCCLURE","MCCABE","MASTERS","MALEY","MAHAN","MACKELL",
		"LARGENT","LABAKI","KULLMAN","KRONENBITTER","KREBS","KOERNER","KIMBROUGH","KILPATRICK","KIGHT",
		"KENDALL","KEHL","KAZANJIAN","KALOYDIS","IRWIN","INGLE","IHINGER","HUTCHESON","HUSTON",
		"HURLEY","HUPP","HUEY","HUCK","HORNBERGER","HOLLOWAY","HOGG","HOFER","HINEBAUGH",
		"HEVAS","HESS","HENSLEY","HENDERSHOT","HELSEL","HEGER","HECKER","HEAGAN","HASSELBERGER",
		"HARDEN","HANE","HAMRICK","HAMBRICK","GUSTAFSON","GUSS","GUERIN","GRODI","GRIFFITHS",
		"GREENE","GRAYSON","GOSSETT","GORLEY","GLAZE","GILLETTE","GESSEL","GERMAN","GENTZLER",
		"GENTILE","GARY","GARLAND","GAREY","FULK","FROST","FRALIX","FOUTY","FORGRAVE",
		"FITZGERALD","FIRTH","FINLEY","FIELD","FESSLER","FENWICK","FANNING","EWING","EVANCHO",
		"EMERICK","LUNDELL","LORENTZ","LOMAX","LLOYD","LINDSEY","LINCICOME","LEOPOLD","LENT",
		"LENHART","LEMMON","LEGRAND","LAWSON","LAWLER","LAVY","ECKELBERRY","EASTWOOD","DUNNINGTON",
		"DOVER","DOSCH","DORSEY","DOLEN","DOBRZYNIECKI","DERBY","DELACRUZ","DAUBENSPECK","DARNER",
		"CUMMINS","CRAWLEY","CRANE","CRAIG","CORP","CORNETT","COMMEANS","COMBS","COLLOPY",
		"COLLIN","COGSWELL","COGANOW","CARRELL","CAROUTHERS","CARMICHAEL","CADE","BUSSEY","BURCHFIELD",
		"BUCK","BRUNER","BRUMAGE","BRUGH","BRADY","BOOKER","BONIFANT","BOLIN","BOESMAN",
		"BOBST","BLANEY","BINCKLEY","BEDNARCZUK","BAXTER","BARKLEY","BARBOUR","BAGENT","AUSKE",
		"ANSEL","ANKRUM","ANGELO","AKERS","ALIFF","AHN","AARON","ABER","BLEAKNEY",
		"BEAVER","BAUMER","BARTON","BARTHEL","BARRIENTOS","BARBER","BALSLEY","AYRES","AXLINE",
		"ASHWORTH","ANGLES","AMBURGEY","ALLENDER","ALDRED","ZORN","ZEIDLER","ZAKANY","ZAK",
		"YERKEY","WUETHRICK","WOOTEN","WOOSLEY","WOODY","WOODWARD","WINSOR","WINGFIELD","WILKEY",
		"WILHITE","WILES","WILCOCK","WIGGINS","WHITED","WHALEY","WERTMAN","WENTZ","WELKER",
		"WEARS","WARFIELD","WALTER","WALSH","WAERS","VANN","ULRY","TURK","TRAINOR",
		"TOMSON","TOMPKINS","TOMAC","TOLLIVER","TOKIE","TITKO","THORNHILL","TEAGARDNER","SWONGER",
		"SWICK","SWEENY","SUTHERS","STRONG","STONEROCK","STOKES","STEPP","STEPHENSON","STARKS",
		"STAPLETON","STANDLEA","SPROUSE","SPRINGER","SPIKER","SOMERS","SLAUGHTER","SITES","SIMPKINS",
		"SILVERTHORN","SHRINER","SHRIMPLIN","SHOOK","SHIRER","SHINN","SHIMER","SHIGLEY","SHELLENBARGER",
		"SERESUN","SEILER","SEENS","SEENES","SEALOCK","SCHUMAKER","SCHUMACHER","SCANLON","SCALES",
		"SALMON","SAGLE","RUSSO","RUSLER","RUNKLE","RUMMER","RUIS","ROUNDTREE","RODRIGUEZ",
		"ROBERTSON","RITTERBECK","RICHMOND","RHEA","REY","RENNER","REICE","REEVES","REEDER",
		"REASONER","RAYMOND","RAWLINGS","RATTIE","RASOR","RANCK","PUCKETT","PRYOR","PRINDLE",
		"PREST","PRESLICKA","POOLE","POCRASS","PLUMADORE","PIPP","PICKRELL","PICKINPAUGH","PETTIT",
		"PETERMAN","PEREZ","PENNY","PENNELL","PENN","PATTON","PASCUAL","PAPE","OVERLY",
		"OLDAKER","ODER","OBERNUEFEMAN","OAKLEY","O'CONNELL","NYKILE","NUSSBAUM","NOTESTONE","NORTH",
		"NOLAN","NOCE","NIXON","NICOLS","NEVILLE","NAGLE","MYUS","MULLENS","MULCARE",
		"MOSES","MOROSKO","MONROE","MOLL","MITZELFELT","MITTON","MINTON","MILTON","MIDDY",
		"MICHALSKI","METZ","MESCHER","MENNENGA","MELL","MEADOWS","MCQUIRE","MCNALLY","MCMILLION",
		"MCLAIN","MCKENNEY","MCGARRY","MCFADIN","MCCUEN","MCCOWEN","MCCONNEL","MCCONAHA","MCCARTNEY",
		"MCCAMEY","MAUTZ","MATTINGLY","MATIS","MATHIS","MATHER","MARTS","MAPLE","MADDOX",
		"LANGFORD","KYSER","KYNNERSLEY","KUHL","KROUSKOUPF","KROFT","KROFFT","KOLSKY","KNOWLES",
		"KNOLL","KNICELY","KNAUP","KLUSCH","KINSEY","KEPLER","KENWORTHY","KENNISON","KEMBLE",
		"KARSE","KANAVEL","JOSSELYN","JERRELLS","JERDAN","JENNISON","HYSON","HURST","HURFORD",
		"HUHN","HUBBLE","HOPKINS","HOLSTEIN","HOLDERMAN","HOGAN","HILTZ","HIGHFIELD","HERDA",
		"HELM","HEINIS","HEDRICK","HEDGES","HECTOR","HEBB","HAZEN","HAWK","HAUGHT",
		"HARTWELL","HARRAH","HANNAHS","HANIFAN","HANES","HAMBEL","HALSEY","HAGUE","HAGAN",
		"GUTHRIE","GULLICHSEN","GULLETT","GUARD","GRULKE","GROVE","GRISSETT","GRIMMETT","GRIM",
		"GRIFFIS","GREULICH","GRAINGER","GOMEZ","GODBY","GODBEE","GOABEE","GLENN","GLANEMAN",
		"GIRTON","GILLILAND","GILLARD","GILKEY","GILES","GENTRI","GEIS","GATTON","GASSAWAY",
		"GASAWAY","GARDENER","GANNON","FRIES","FRANCSIS","FOIT","FLUHART","FLESHER","FISHBAUGH",
		"FINCK","FELIX","EVILSIZER","ERWIN","ENGLAND","EMERSON","DUVALL","LYTTON","LYDIC",
		"LUTTRELL","LOREY","LOOMAN","LONGFELLOW","LOERA","LOCKHART","LOCKARD","LIPPS","LINGLE",
		"LIGHTLE","LESHER","LEONARD","LEFTRIDGE","LEEDHAM","LEAKE","JACK","ISER","INMAN",
		"IMLAY","IMBODEN","DURAN","DUESENBERRY","DOVENBARGER","DOUGHTY","DONOHOE","DODGE","DODD",
		"DAW","ELLINGER","ELDER","EATON","CUMMINGS","CRUZ","CRUMBAKER","CROUSO","CROSLAND",
		"CROMWELL","CRAWMER","CORDELE","DINAN","DILLSAVER","DIEHL","DENTON","DENISE","DELONG",
		"CONWAY","CONNOR","CONKLIN","CONE","COLLAGE","COLE","COLDREN","CHIAPPONE","COSS",
		"CORSON","CHEECK","CHAFIN","CATO","CASTLE","CASSATT","CARREL","CARNER","BRUNTON",
		"COCKRELL","COBURN","COBB","COAKLEY","CLOUSE","CINQUEPALMI","CHIDESTER","BRUMBAUGH","BROWNFIELD",
		"BROSIE","BRATTON","BRADFORD","BOYNTON","BOWSHIER","BOWSER","BOWLEY","BOWENS","BOTKIN",
		"BONICE","BOLAND","BOEHN","BLOCK","BLAGG","BLACKBURN","BIRKHEIMER","BILLINGSLEY","BIESSER",
		"BICHARD","BIBLE","BENWARE","BEERS","CALHOUN","BYERS","BURGETT","BURG","ALBERT",
		"ACEVEDO","ABELLA","A'NEAL","ACKESON","AGAR","AEBY","AITKEN","FLORES","FISH",
		"FINTON","FINAN","FIKES","FERNANDEZ","FARSON","FARROW","FARQUHAR","FALLON","FALING",
		"ETHELL","ESTERHAY","ERNST","ENZOL","ELLIOT","ELEKES","EICHEL","EASTLAND","EAL",
		"DUP","DUNGEE","DUMONT","DUFFEE","DUDGEON","DRUMM","DOWNEY","DIPPRE","DIMARIO",
		"DILL","DIGIANDO","DIERKES","DICK","DIAZ","DEWEY","DEWEES","DEVER","DETERS",
		"DENN","DEMENT","DELTORO","DEGRAW","DEEDS","DEBELL","DARLING","DANNER","CURRENT",
		"CURLEY","CRUSE","CRUM","CROTZER","CREMEANS","CRELLIN","COULSON","COTTRILL","COTTON",
		"COTE","COSTA","CORONADO","CORNELISON","CONNER","CONASTER","COLVIN","COLEBANK","COLBERT",
		"COCONIS","COBLE","CLIFTON","CLEWIS","CHRISTENSEN","CHEVALIER","CHEMA","CAVINEE","ZULLO",
		"ZEIGLER","YOHO","WYNSTRA","WYLIE-MCELHANEY","WYERS","WRITESEL","WREEDE","WORTMAN","WORKMAN",
		"TOMLINSON","TOMBLIN","TOLLETT","TIPPLE","TIBBALS","TANDY","SWORD","SWITZER","SWINEHART",
		"SWIGERT","SWIGER","SWENDRYNK","SWENDRYCH","SWEIGART","SWEARINGEN","SUMNER","STURTZ","STUCK",
		"STUBBS","STRUNK","STROUP","STRICKLER","STRICKLAND","STOUT","STOCKER","STINER","STEER",
		"STARK","STALL","STAFFEY","STACKHOUSE","SPUNG","SPRANKLER","SPRAGG","SPITZER","SOLLER",
		"SOLIS","SNEIDER","SNEDDON","SMITLEY","SMEDLEY","SMALLS","SLOVICK","SKINNER","SISCO",
		"SINDLEDECKER","SICKLE","SHUSTER","SHUGERT","SHREWSBURY","SHIPE","SHIELDS","SHERRICK","SHERMAN",
		"SHEELER","SHAWGER","SHARROCK","SHALOSKY","SEVY","SETTLES","SENIG","SELLARS","SECKMAN",
		"SEARLES","SAYRE","SAVORY","SARVER","SARTIN","SARCHET","SAMPSON","SAMPSEL","RUST",
		"RUIZ","WOODSIDE","WOLLANGUR","WOLFF","WITHERS","WISOR","WINGROVE","WILLIBY","WILLETTE",
		"WILLCUTT","WHITT","WHITEHEAD","WHITEHAIR","WHISSEN","WETZEL","WESNEY","WEIL","WEIDRINGER",
		"WEESE","WASHER","WARTENBEE","WALLER","WALLECK","WALL","WALDREN","WAKLEY","WAGGLE",
		"VOLLAND","VINNEY","VIENO","VICKROY","VERNICEK","VENSIL","VENABLE","VARNEY","VARGO",
		"VANVORHIS","VANORDEN","VANHOUGHTON","VANHORN","VANFOSSEN","VANDERMARK","VANDAGRIFF","VAN NESS","VAN HALEN"
	};

	private static String[] streetNames = { "ABERDEEN", "ABINGTON", "ACADEMY",
			"ADAIR", "ADAMS", "ADAMSVILLE", "AERYVIEW", "AGINES", "AIRPORT",
			"AIRWOOD", "AKRON", "ALAMEDA", "ALBERT", "ALBRIGHT", "ALBURN",
			"ALEXIS", "ALFRED", "ALICE", "ALKIRE", "ALLEN", "ALLISON", "ALVIN",
			"AMBARASSDOR", "AMBER", "AMHURST", "AMSTERDAM", "ANDY", "ANTIGUA",
			"APPLEGATE", "ARBORWOOD", "ARCADIA", "ARCH", "ARCHER", "ARLINGTON",
			"ARMCO", "ARMSTRONG", "ARNOLD", "ARROWHEAD", "ARTHUR", "ASHBURTON",
			"ASHLEY", "ASPEN", "ATHENA", "ATHENS", "ATLANTIC", "AUBURN",
			"AUSTIN", "AVALON", "AVON", "AXLINE", "AYERS", "BABBS", "BACK",
			"BAGLEY", "BAILEY", "BAIRD", "BAKER", "BALL", "BALLARD", "BALLOV",
			"BANK", "BARDITH", "BARKEY", "BARKLEY", "BARNES", "BARR", "BASIL",
			"BASIN", "BATEMAN", "BAUGHMAN", "BEAM", "BEARD", "BEATTY",
			"BEAUTY", "BEECH", "BEECHCREEK", "BEECHMONT", "BEELINE", "BELDEN",
			"BELL", "BELLFLOWER", "BELLVIEW", "BELLWOOD", "BELMONT",
			"BENJAMIN", "BENNETT", "BENWOOD", "BERKLEY", "BEST", "BETHESDA",
			"BEULAH", "BEVERLY", "BEXLEY", "BILLINGSLEY", "BISSETT", "BISSON",
			"BLACK", "BLACKBURN", "BLACKRUN", "BLACKSTONE", "BLACKWOOD",
			"BLAINE", "BLALOCK", "BLANDY", "BLENNERHASSETT", "BLOCKSOM",
			"BLOOMFIELD", "BLOSSOM", "BLUE", "BLUFF", "BOBBY", "BODMANN",
			"BOGGS", "BOLEN", "BOLTON", "BONAPARTE", "BONIFIELD", "BONNAIR",
			"BONSELS", "BOSTON", "BOTTOM", "BOWMAN", "BOWSER", "BOWTOWN",
			"BRADINGTON", "BRANCH", "BRANDYWINE", "BREEZEWOOD", "BREWERS",
			"BRIARBUSH", "BRIARCLIFF", "BRIARLEIGH", "BRICK", "BRIDGE",
			"BRIGHTON", "BRILL", "BRISTOL", "BRITTON", "BROAD", "BROADVUE",
			"BROADWAY", "BROOKFIELD", "BROOKOVER", "BROOKSIDE", "BROWN",
			"BROWNS", "BRYAN", "BUCK", "BUCKEYE", "BUCKINGHAM", "BURBANK",
			"BURLINGTON", "BURNELL", "BURNET", "BURNS", "BUSCH", "BUTLER",
			"BUTTER", "BUTTERMILK", "BYRNE", "CALEB", "CALVERT", "CAMBON",
			"CAMBRIDGE", "CAMDEN", "CAMP", "CAMPBELL", "CANAL", "CANDLESTICK",
			"CANEWOOD", "CANFIELD", "CANNELVILLE", "CANNEVILLE", "CANNON",
			"CARBONDALE", "CAREY", "CARL", "CARLISLE", "CARLTON", "CARLYSLE",
			"CARMEN", "CAROL", "CARPENTER", "CARROLL", "CARSON", "CARVER",
			"CASS", "CASTON", "CASTOR", "CATALPA", "CATHY", "CATT", "CATTAIL",
			"CATTLE", "CECIL", "CEDAR", "CEDARHURST", "CELINA", "CEMENTARY",
			"CEMETERY", "CENTER", "CENTRAL", "CERAMIC", "CHALFANT",
			"CHANDLERSVILLE", "CHAPMAN", "CHARDON", "CHARLENE", "CHARLES",
			"CHASE", "CHATAUQUA", "CHATHAM", "CHENEY", "CHERLICK", "CHERRY",
			"CHESAPEAKE", "CHESTER", "CHESTERFIELD", "CHESTNUT", "CHEVINGTON",
			"CHEWELAH", "CHILDRENS", "CHILLICOTHE", "CHINA", "CHOCTAW",
			"CHRISTOPHER", "CHRISTY", "CHURCH", "CHURCHFIELD", "CIRCLE",
			"CIRCLEVILLE", "CLAIRBOURNE", "CLAIRE", "CLARENCE", "CLARENDON",
			"CLARICE", "CLARK", "CLARY", "CLAY", "CLAYSVILLE", "CLEARCREEK",
			"CLEAREY", "CLEARPORT", "CLEARVIEW", "CLEVE", "CLEVELAND",
			"CLEVENGER", "CLIFFROCK", "CLIFFWOOD", "CLINTON", "CLOVER",
			"CLOVERIDGE", "CLYDE", "COBURG", "COCHRAN", "CODELL", "COHEN",
			"COLBURN", "COLLEGE", "COLLINGWOOD", "COLLINS", "COLONY",
			"COLUMBIA", "COLUMBUS", "COMIN", "COMMISSIONER", "COMMONWEALTH",
			"CONN", "CONVERS", "COOPERMILL", "COOPERRIDERS", "COOPERWELL",
			"CORNELL", "CORNSTILL", "CORONADO", "CORVUS", "CORWIN", "COSGRAVE",
			"COSHOCTON", "COTTAGE", "COUNTISS", "COUNTRYSIDE", "COURT", "COVE",
			"COVENTRY", "COWDEN", "CRANFIELD", "CRAWFORD", "CREAMERY",
			"CREEDMOOR", "CREEKVIEW", "CRESTWAY", "CROCK", "CROOKS", "CROSIER",
			"CROSS", "CROSSGATE", "CROW", "CROWN", "CULBERTSON", "CURTIS",
			"DADS", "DAISY", "DALE", "DALLMAN", "DANA", "DANIELS", "DANVILLE",
			"DARCIE", "DARLA", "DARLINGTON", "DATE", "DAVIS", "DAWNLIGHT",
			"DAWSON", "DEARBORN", "DECEMBER", "DECROW", "DEER", "DEERFIELD",
			"DEERPATH", "DEEWOOD", "DELLWOOD", "DELMONT", "DELWOOD", "DENBIGH",
			"DENLINGER", "DENMARK", "DENNING", "DENNIS", "DENNY", "DEPOT",
			"DETROIT", "DEVIN", "DEVLIN", "DEWEY", "DIAGONAL", "DICKINSON",
			"DICKSON", "DIETZ", "DILLON", "DISCOVERY", "DIXIE", "DIXON",
			"DOGWOOD", "DONA", "DONALD", "DOOLEYS", "DOROTHY", "DORU",
			"DOUGLAS", "DOWLING", "DOWNARD", "DOWNING", "DRAGOO", "DRESDEN",
			"DRYDEN", "DUNDEE", "DUNHAM", "DUNZWEILER", "DURBAN", "DUVALL",
			"DYER", "EAST", "EASTER", "EASTERN", "EASTFIELD", "EASTLAWN",
			"EASTMAN", "EASTMOOR", "EASTPORT", "EASTVIEW", "EASTWARD",
			"EASTWOOD", "EATON", "ECHO", "EDALBERT", "EDDIE", "EDDY", "EDERER",
			"EDGEWATER", "EDISON", "EDNA", "EDWARD", "EDWARDS", "ELDWOOD",
			"ELFIN", "ELIDA", "ELIZABETH", "ELLEN", "ELLER", "ELLIS",
			"ELLSWORTH", "ELMVILLE", "EMILY", "ENGLEWOOD", "ENON", "EPPLEY",
			"ERIE", "ERIN", "ESSEX", "EUCLID", "EVANS", "EVANSPORT", "EVELYN",
			"EVERGREEN", "EWING", "EXCHANGE", "EXTENSION", "FAIR", "FAIRALL",
			"FAIRBANKS", "FAIRCREST", "FAIRMONT", "FAIRMOUNT", "FAIRVIEW",
			"FAIRWAY", "FALLSBURG", "FALT", "FARSON", "FAWN", "FAYE",
			"FAYETTE", "FEDERAL", "FERNCLIFF", "FERNSTONE", "FERRELL", "FESS",
			"FIELD", "FINDLEY", "FIRST", "FISHERS", "FITZGERALD", "FLEEK",
			"FLEMING", "FLINT", "FLINTRIDGE", "FLINTWOOD", "FLORENCE",
			"FOREST", "FORRY", "FOSTER", "FOUNDS", "FOUNTAIN", "FOWLERS",
			"FOXFIRE", "FRAME", "FRANCIS", "FRANKLIN", "FRAZEYSBURG",
			"FREEBORN", "FREEDOM", "FRICK", "FRIENDSHIP", "FRISCO", "FRITTER",
			"FRONT", "FRONTIER", "FULBROOK", "FULTON", "FULTONROSE",
			"GALBRAITH", "GALENA", "GALIGHER", "GALIGHNER", "GALLIA", "GALWAY",
			"GANT", "GANTZ", "GARDEN", "GARDENWAY", "GAREY", "GARFIELD",
			"GARNER", "GARRELL", "GARRETT", "GARST", "GASLIGHT", "GAYLA",
			"GENESSEE", "GEORGE", "GEST", "GIBBARD", "GIFFORD", "GILBERT",
			"GLADE", "GLENA", "GLENAVEN", "GLENDALE", "GLENHAVEN", "GLENN",
			"GLENWILLOW", "GLENWOOD", "GLESSNER", "GODDARD", "GOMBER",
			"GOOSECREEK", "GORDON", "GORRELL", "GORSUCH", "GOSLEN", "GRACE",
			"GRAFFIS", "GRAND", "GRANDVIEW", "GRANGER", "GRANT", "GRANVILLE",
			"GRATIOT-NEWARK", "GRAY", "GRAYLOCK", "GREEN", "GREENBRIAR",
			"GREENBRIER", "GREENGOLD", "GREENHOUSE", "GREENVILLE", "GREENWOOD",
			"GREINER", "GRIEVES", "GROVE", "GUAVA", "HAESSLER", "HALE", "HALL",
			"HAMBURG", "HAMILTON", "HAMLINE", "HAMPTON", "HANAWALT", "HANNAH",
			"HANNAWALT", "HANOVER", "HANSON", "HARBOR", "HARDESTY", "HARDING",
			"HARDY", "HARKERS", "HARLAN", "HARMON", "HARMONY", "HARPER",
			"HARRIS", "HARRISON", "HARSHMAN", "HARTFORD", "HARTMAN",
			"HARTVILLE", "HARTWELL", "HARVEY", "HAUGHT", "HAWK", "HAWKES",
			"HAYES", "HAZEL", "HAZLETT", "HEATH", "HEBER", "HEBRON", "HECKAK",
			"HECKEL", "HEDGEWOOD", "HELENE", "HELPAR", "HENDERSHOT", "HENRY",
			"HERITAGE", "HERRON", "HEWITT", "HICKAM", "HICKMAN", "HICKORY",
			"HICKS", "HIDEAWAY", "HIGGINS", "HIGH", "HIGHLAND", "HIGHVIEW",
			"HILBISH", "HILDRETH", "HILL", "HINMAN", "HOGANS", "HOGE",
			"HOILES", "HOLBEIN", "HOLBERT", "HOLLIDAY", "HOLMES", "HOME",
			"HOMELESS", "HOMER", "HOMES", "HOMESTEAD", "HOMEWOOD", "HOOVER",
			"HOPEWELL", "HOSPITAL", "HOWARD", "HOWELL", "HUDSON", "HUEY",
			"HUGHES", "HUMPHREY", "HUNT", "HUNTER", "HUNTERDON", "HUNTINGTON",
			"IDAHO", "IDLEWOOD", "ILDEWOOD", "ILIAMNA", "IMLAY",
			"INDEPENDENCE", "INDIANA", "INDIANOLA", "INWOOD", "IRELAND",
			"IRON", "ISLAND", "JACKSON", "JAMES", "JAMESTOWN", "JANNETT",
			"JEFFERSON", "JENKINS", "JENSEN", "JESSAMINE", "JEWETT", "JEWITT",
			"JODY", "JOHN", "JOHNSON", "JOHNSTOWN", "JONATHAN", "JONES",
			"JORDAN", "JOYCE", "JUANITA", "JULIAN", "JUNIPER", "KAHLER",
			"KATHERINE", "KAUFFMAN", "KEARNS", "KEEN", "KEGS", "KELLY",
			"KENNEDY", "KENNY", "KENSINGTON", "KENTON", "KERRI", "KETTERING",
			"KEVROB", "KEYSTONE", "KIBLER", "KIMES", "KING", "KINGS",
			"KINGSLEY", "KINGSWOOD", "KINSMAN", "KINZEL", "KIRK", "KLOTZ",
			"KNIPE", "KNOX", "KOPCHAK", "KOSSUCH", "LACON", "LAFAYETTE",
			"LAGONDA", "LAKE", "LAKESIDE", "LAKEWOOD", "LAMBERT", "LANCASTER",
			"LANCASTER-CHILLICOTH", "LANDER", "LANEWAY", "LANGAN", "LARK",
			"LARKSPUR", "LARRY", "LARZELERE", "LASALLE", "LASHLEY", "LAUREL",
			"LAVONA", "LAWHEAD", "LAWN", "LAWNDALE", "LAWSON", "LAWYERS",
			"LAYTON", "LAZELERE", "LECTRIC", "LEDBETTER", "LEEDOM", "LEFFLER",
			"LEFTER", "LEGION", "LENOX", "LENT", "LEON", "LEONARD",
			"LEONARDVILLE", "LESLIE", "LESSLAR", "LEWIS", "LEXINGTON",
			"LIBERTY", "LICKING", "LILLIAN", "LIMA", "LIMESTONE", "LINCOLN",
			"LINCOLNWAY", "LINDALE", "LINDBERGH", "LINDEN", "LINDSAY", "LINN",
			"LINWOOD", "LISA", "LITHOPOLIS", "LIVINGSTON", "LOCK", "LOCKSMITH",
			"LOCUST", "LODGE", "LOMITA", "LONDON", "LONG", "LOOKOUT", "LOST",
			"LOUDON", "LOUISE", "LOVERS", "LUBRING", "LUCAS", "LUCASBURG",
			"LUCK", "LUNDGREN", "LUTZ", "MACEDONIA", "MACKENZIE", "MADISON",
			"MAILEY", "MAIN", "MALIBU", "MANNING", "MANOR", "MANSFIELD",
			"MAPLE", "MAPLECRAFT", "MAPLEVIEW", "MAPLEWOOD", "MARCHMONT",
			"MARIETTA", "MARION", "MARK", "MARKET", "MARKETING", "MARLO",
			"MARNE", "MARSHA", "MARSHDALE", "MARTIN", "MARTINEL", "MARY",
			"MAST", "MATTHEWS", "MAYFAIR", "MAYSVILLE", "MCARTHUR", "MCCARLEY",
			"MCCASLIN", "MCCLAIN", "MCCLURE", "MCCONNELL", "MCCONNELLSVILLE",
			"MCDANIEL", "MCDONALD", "MCFARLAND", "MCINTIRE", "MCKAIG",
			"MCKEEVER", "MCKINLEY", "MCMILLAN", "MCOWENS", "MEAD", "MEADOW",
			"MEADOWBROOK", "MEADOWHAVEN", "MEADOWOOD", "MECHANICSBURG", "MEEK",
			"MELICK", "MELROSE", "MEMORY", "MERIDIAN", "MERIWETHER", "MERLIN",
			"MERRIAM", "MERRICK", "MERRIMAC", "MERRYHILL", "MERSHON",
			"MESSIMER", "METRO", "MIAMI", "MICHAEL", "MICHIGAN", "MIDDLE",
			"MIDDLEFORK", "MIDDLETON", "MIDWAY", "MILAGRA", "MILITARY", "MILL",
			"MILLER", "MILLERS", "MILTON", "MINER", "MISSOURI", "MITCHELL",
			"MOCCASIN", "MOCK", "MOHAWK", "MOLLYSROCK", "MONA", "MONROE",
			"MONTAGUE", "MONTGOMERY", "MOONLIGHT", "MOORE", "MOOREHEAD",
			"MOORES", "MOOREWOOD", "MORGAN", "MORGANTOWN", "MORGANVILLE",
			"MORNINGSTAR", "MORRISON", "MORSE", "MOUND", "MOXADARLA",
			"MOXAHALA", "MUIRWOOD", "MULBERRY", "MUNDY", "MUNSON", "MURRAY",
			"MUSKINGUM", "MUSSELMAN", "MYRTLE", "NANCY", "NARROWS", "NATIONAL",
			"NAVY", "NEAL", "NEIL", "NELSON", "NEPTUNE", "NEWARK", "NEWGATE",
			"NEWLON", "NEWMAN", "NEWPORT", "NICHALAS", "NOLAN", "NONE",
			"NOR-BIXBEY", "NORA", "NORFIELD", "NORMANDY", "NORRIS", "NORTH",
			"NORTHCREST", "NORTHLAND", "NORWICH", "NORWOOD", "NOTTINGHAM",
			"NOTTINGHAMSHIRE", "NUGENT", "OAKLAND", "OAKWOOD", "OBETZ",
			"ODELL", "OHIO", "OKEY", "OLIVE", "OLNEY", "ONTARIO", "OPERA",
			"ORANGE", "ORCHARD", "ORDERS", "ORTON", "OSAGE", "OSCEOLA",
			"OTTERBEIN", "OVERLOOK", "OWENS", "OXFORD", "PAINT", "PALAMINO",
			"PALLAS", "PALMER", "PALMERAWAY", "PALMWOOD", "PALOMINO",
			"PARAGON", "PARISH", "PARK", "PARKER", "PARKS", "PARKVIEW",
			"PARKWAY", "PARKWOOD", "PARLIAMENT", "PARRY", "PARTRIDGE", "PATCH",
			"PATRICIA", "PEACHBLOW", "PEAR", "PEARL", "PEMBROKE", "PENN",
			"PENNEY", "PENNISULA", "PENNSYLVANIA", "PENRICK", "PERDUE",
			"PERINE", "PERKINS", "PERRY", "PERRYTON", "PERSHING", "PETERS",
			"PETERSBURG", "PETERSON", "PFEIFER", "PFEIFFER", "PHILADELPHIA",
			"PHILLIPS", "PICKWICK", "PIERCE", "PIKE", "PINE", "PINECREST",
			"PINETOWN", "PINEVIEW", "PINEWOOD", "PINKERTON", "PINKLEY",
			"PIONEER", "PIPER", "PLAINFIELD", "PLANTATION", "PLAYFORD",
			"PLEASANT", "PLEASANTVIEW", "PLEASANTVILLE", "POINTE", "POPLAR",
			"PORTAGE", "PORTER", "PORTLAND", "POTTERS", "POTTS", "POWELL",
			"PRAME", "PRATT", "PRICE", "PRINCETON", "PRIOR", "PRISON",
			"PROMWAY", "PROSPECT", "PRYOR", "PUBLIC", "PURDY", "PURVIS",
			"PUTNAM", "QUARRY", "QUICK", "QUINCY", "QUINLAN", "RACE", "RADNOR",
			"RAIDERS", "RAILROAD", "RAINS", "RAINTREE", "RANGE", "RANKIN",
			"RANSBOTTOM", "RAVEN", "RAVENWOOD", "RAWSON", "READING", "REAM",
			"REDMAN", "REDONDO", "REED", "REEVES", "REHL", "RESTLESS",
			"REYNOLDS", "RHONDA", "RICE", "RICHARDS", "RICHEY", "RICHMAN",
			"RICHMOND", "RICHVALE", "RICHWOOD", "RIDER", "RIDGE", "RIDGEFIELD",
			"RIDGELAND", "RIDGEVIEW", "RIDGEWOOD", "RIGBY", "RIGGIN", "RIGNY",
			"RITCHEY", "RITENOUR", "RIVER", "RIVERSIDE", "RIVERVIEW",
			"ROADAYLE", "ROBERTSON", "ROBIN", "ROBINSON", "ROBINWOOD", "ROCK",
			"ROCKVILLE", "ROEMER", "ROLAND", "ROLLINS", "RONDAYLE",
			"ROOSEVELT", "ROPER", "ROSE", "ROSEVILLE", "ROSEWOOD", "ROWLAND",
			"ROYALTON", "ROYMA", "RUCKER", "RUNYAN", "RUSSELL", "RUSTLE",
			"RUTH", "RYAN", "SALEM", "SALGARBER", "SALLY", "SALTZGABER",
			"SAMPSON", "SAMUEL", "SAND", "SANDHURST", "SANDRA", "SANDUSKY",
			"SANDVIK", "SANTOY", "SARAH", "SCARBOROUGH", "SCENIC", "SCHAUM",
			"SCHNEIDER", "SCHOLL", "SCHOOL", "SCHULER", "SCHULTZ", "SCHWALLIE",
			"SCOTT", "SCOUT", "SEALOVER", "SEAMAN", "SEBORN", "SELLS",
			"SELSAM", "SENATOR", "SEROCO", "SEVALL", "SEVERT", "SEWARD",
			"SEYMORE", "SHADY", "SHAGBARK", "SHALIMAN", "SHANDON", "SHARON",
			"SHARONWOOD", "SHASTA", "SHAW", "SHAWNEE", "SHEANDOAH", "SHEILA",
			"SHELLHART", "SHENANDOAH", "SHEPHERD", "SHERBORNE", "SHERIDAN",
			"SHERMAN", "SHERWOOD", "SHINDERN", "SHINICK", "SHINNICK",
			"SHIPLETT", "SHOOP", "SHORE", "SHORT", "SHUMAKER", "SIBLEY",
			"SILLIMAN", "SILMORE", "SKYLINE", "SKYVIEW", "SLACK", "SMITHFIELD",
			"SMITHWOOD", "SNOKE", "SNYDER", "SOFIN", "SOLIDA", "SOMERS",
			"SOMERSET", "SONORA", "SOUDER", "SOUTH", "SOUTHARD", "SOUTHEAST",
			"SOUTHERN", "SOUTHWARD", "SPANGLER", "SPARLING", "SPELLMAN",
			"SPENCE", "SPENCER", "SPIELBUSCH", "SPRATT", "SPRING",
			"SPRINGDALE", "SPRUCE", "SPRY", "STACY", "STALDER", "STALLING",
			"STANLEY", "STANSBERRY", "STANTON", "STANWAY", "STATE", "STEELE",
			"STEIN", "STEPHENS", "STEVENS", "STEVY", "STEWART", "STIERS",
			"STILLMEADOW", "STILLWELL", "STINE", "STIVER", "STOKELY", "STONE",
			"STONECREEK", "STORMONT", "STOUT", "STOUTSVILLE", "STRAWBERRY",
			"STREET", "STURTZ", "STYGLER", "SUDBURY", "SUGARGROVE",
			"SUGARTREE", "SUMMIT", "SUNDALE", "SUNFLOWER", "SUNKEL", "SUNRAY",
			"SUNRISE", "SUNSET", "SUPERIOR", "SURGER", "SWANS", "SWARTZ",
			"SWINGLE", "SYCAMORE", "TALFORD", "TALLEY", "TAMARRON", "TAMMY",
			"TANNEHILL", "TARKMAN", "TAYLOR", "TEAKWOOD", "TEDRICK", "TEMPLE",
			"TERRACE", "TERRY", "THEOBALD", "THIRD", "THOMAS", "THOMPSON",
			"THORN", "THORNBERRY", "THORNHILL", "THURMAN", "TIFFANY",
			"TILESTON", "TITUS", "TODD", "TONI", "TOWERS", "TOWN", "TRABUE",
			"TRACI", "TRACO", "TRANQUILITY", "TREEHOUSE", "TREMONT", "TREND",
			"TRIDELPHIA", "TUPEDO", "TURNER", "TURTLE", "TUSCARAWAS",
			"TWIMENHILL", "TYMAN", "UNDERWOOD", "UNEEDA", "UNION", "UNKNOWN",
			"VALLEY", "VANCE", "VAUGHN", "VENTURE", "VENUS", "VERNON",
			"VETTER", "VICKI", "VICTORY", "VILLA", "VILLAGE", "VINE", "VINSEL",
			"VIRGINIA", "VISTA", "VROOM", "WABASH", "WACKER", "WAKATOMIKA",
			"WALDOLF", "WALKER", "WALL", "WALLWORK", "WALNUT", "WALTER",
			"WALTHAM", "WARD", "WARGO", "WARNER", "WARNERS", "WARREN",
			"WARWICK", "WASHINGTON", "WATER", "WATERS", "WATKINS", "WATSON",
			"WATTS", "WAYNE", "WEAVER", "WEBB", "WEBSTER", "WEDGEWOOD",
			"WEEDON", "WELLER", "WELLS", "WENTZ", "WESSEX", "WEST",
			"WESTBOURNE", "WESTERN", "WESTMOOR", "WESTMORE", "WESTWOOD",
			"WETSELL", "WHALEY", "WHEATLAND", "WHEELABOUT", "WHEELER",
			"WHEELING", "WHIPPLE", "WHITES", "WHITMAN", "WILHELM", "WILKINS",
			"WILLIAMS", "WILLIS", "WILLOW", "WILMER", "WILMINGTON", "WILSHIRE",
			"WILSON", "WINDING", "WINDMILL", "WINDSONG", "WINFIELD",
			"WINLWOOD", "WINTER", "WINTON", "WISE", "WISTERIA", "WOGAN",
			"WOLFE", "WOLFORD", "WOODBERRY", "WOODBROOK", "WOODLAND",
			"WOODLAWN", "WOOLPER", "WORKMAN", "WORTMAN", "WREXHAM", "YALE",
			"YINGLING", "YOST", "YOUNG", "ZANE", "ZANESVILLE", "ZELLA" };

	private static String[] addressSuffixes = { "AVE", "BLVD", "CIR", "CRES",
			"CT", "DR", "HTS", "HWY", "LN", "PARK", "PATH", "PIKE", "PKWY",
			"PL", "RD", "RDG", "RUN", "SQ", "ST", "STA", "TER", "TRL", "WAY" };

	private static String[] cities = { "ADA", "ADAMS MILLS", "ADAMSVILLE",
			"AKRON", "ALBANY", "ALLIANCE", "AMANDA", "AMESVILLE", "ANAHEIM",
			"ANDOVER", "ANMOORE", "ASHEVILLE", "ASHLAND", "ASHTABULA",
			"ASHVILLE", "ATHENS", "AVA", "AVON", "AVONDALE", "BAINBRIDGE",
			"BALTIMORE", "BANGOR", "BARBERTON", "BARNESVILLE", "BATAVIA",
			"BEACH CITY", "BEAVER FALLS", "BEDFORD", "BELLAIRE",
			"BELLEFONTAINE", "BELLVILLE", "BELPRE", "BEREA", "BERLIN CENTER",
			"BETHESDA", "BEVERLY", "BILLINGS", "BLUE ROCK", "BOLIVAR",
			"BOWLING GREEN", "BREMEN", "BROADVIEW HEIGHTS", "BROOK PARK",
			"BROWNSVILLE", "BRUNSWICK", "BRUSE MISSISSIPPI", "BRYAN",
			"BUCKEYE LAKE", "BUFFALO", "BUNNELL", "BURG HILL", "BURGETTSTOWN",
			"BYESVILLE", "CADIZ", "CALDWELL", "CALDWELL,", "CAMBRIDGE",
			"CANNELSVILLE", "CANNELVILLE", "CANTON", "CAPE CANAVERAL",
			"CAPRON", "CARBON HILL", "CARLWICK", "CARROLL", "CARROLLTON",
			"CELINA", "CENTERBURG", "CHANDLERSVILLE", "CHANDLERSVLLE",
			"CHARDON", "CHESTERHILL", "CHESTERTOWN", "CHESTERVILLE",
			"CHICKASHA", "CHILICOTHE", "CHILLICOTHE", "CHULA VISTA",
			"CINCINNATI", "CIRCLEVILLE", "CLAIRTON", "CLARITIN", "CLARKSBURG",
			"CLEVELAND", "CLEVELAND HEIGHTS", "COAL RUN", "COLUMBUS",
			"COLUMBUS GROVE", "CONESVILLE", "CONNEAUT", "CONWAY",
			"COON RAPIDS", "CORNING", "COSHOCTON", "COTTONWOOD",
			"CRANBERRY TWP", "CREOLA", "CRESTON", "CROOKSVILLE", "CROSS LANES",
			"CUMBERLAND", "DAYTON", "DEFIANCE", "DEFUNIAK SPRINGS", "DELAWARE",
			"DELEWARE", "DELPHOS", "DELTA", "DENISON", "DENTON", "DEXTER CITY",
			"DOVER", "DRESDEN", "DU BOIS", "DUBLIN", "DUNCAN FALLS",
			"E FULTONHAM", "E. FULTONHAM", "EAST CANTON", "EAST FULTONHAM",
			"EAST LIVERPOOL", "EAST SPARTA", "EATON", "EL SEGUNDO", "ELIRIA",
			"ELYRIA", "ENGLEWOOD", "ESSEXVILLE", "EVERETT", "FAIRBANKS",
			"FAIRBORN", "FAIRFIELD", "FAIRLAWN", "FAIRMONT", "FAYETTE",
			"FINDLAY", "FLAT ROCK", "FLEMING", "FORT CAMPBELL", "FORT DRUM",
			"FORT MYERS", "FORT RICHARDSON", "FORT WAYNE", "FORT WORTH",
			"FRANKFORT", "FRAZEYSBURG", "FREDERICKSBURG", "FREDERICKTOWN",
			"FREEPORT", "FREMONT", "FRESNO", "FT WAYNE", "FULTON", "FULTONHAM",
			"GAHANNA", "GALENA", "GALION", "GALLIPOLIS", "GALLOWAY", "GAMBIER",
			"GAYSPORT", "GEORGETOWN", "GLENDORA", "GLENFORD", "GLOUSTER",
			"GRANVILLE", "GRATIOT", "GREENFIELD", "GREENSBURG", "GREENVILLE",
			"GRIFFIN", "GROVE CITY", "GROVEPORT", "GUERNSEY", "HAGERSTOWN",
			"HAINES CITY", "HAMILTON", "HARKER HEIGHTS", "HARRISON",
			"HASTINGS", "HEATH", "HEBRON", "HEDGEFIELD", "HELENA", "HEMLOCK",
			"HERMITAGE", "HERNANDO", "HICKSVILLE", "HILLIARD", "HILLSBORO",
			"HILTON HEAD", "HOLLY HILL", "HOPEWELL", "HOPKINS", "HOT SPRINGS",
			"HOUSTON", "HOWARD", "HUBBARD", "HUBER HEIGHTS", "HUDSON",
			"HUNTSVILLE", "INDEPENDENCE", "INDIANA", "INDIANAPOLIS", "INKSTER",
			"IRONTON", "IRVING", "JACKSON", "JACKSON CENTER", "JERSEY CITY",
			"JERUSALEM", "JOHNSTOWN", "JUNCTION CITY", "JUNCTION CITY,",
			"KANSAS CITY", "KENT", "KENTON", "KETTERING", "KILBUCK",
			"KILLBUCK", "KIMBOLTON", "KINGSTON", "KIRKERSVILLE", "KISSIMMEE",
			"KITTS HILL", "LADOGA", "LAKESIDE PARK", "LAKEWOOD", "LANCASTER",
			"LANGO", "LAS VEGAS", "LAURELVILLE", "LEBANAN", "LEBANON", "LEOLA",
			"LIBERTY", "LIMA", "LISBON", "LIVONIA", "LOCKBOURNE", "LOGAN",
			"LOGANSPORT", "LOGANVILLE", "LONDON", "LONDONBERRY", "LONDONDERRY",
			"LONG BEACH", "LORAIN", "LORE CITY", "LOUISVILLE", "LUCASVILLE",
			"MACEDONIA", "MADISON", "MALTA", "MANSELONE", "MANSFIELD",
			"MANTUA", "MARIETTA", "MARINS FERRY", "MARION", "MARTINS FERRY",
			"MARYSVILLE", "MASSILLON", "MAUMEE", "MC ARTHUR",
			"MC CONNELSVILLE", "MCCONNELSVILLE", "MECHANICSBURG", "MEDINA",
			"MELBOURNE", "MEMPHIS", "MESA", "MIDDLEPORT", "MILFORD",
			"MILLERSBURG", "MILLERSPORT", "MILLINGTON", "MILLTOWN", "MINERVA",
			"MOBILE", "MONCLOVA", "MONROE", "MONTICELLO", "MORRISTOWN",
			"MORROW", "MOUNT GILEAD", "MOUNT PERRY", "MOUNT VERNON",
			"MT PERRY", "MT STERLING", "MT. PERRY", "MT. STERLING",
			"MT. VERNON", "MUNCIE", "MURRAY CITY", "MYRTLE BEACH", "NAPOLEON",
			"NASHPORT", "NASHVILLE", "NELSONVILLE", "NEW ALBANY", "NEW BOSTON",
			"NEW CARLISLE", "NEW CONCORD", "NEW HAVEN", "NEW LEXINGTON",
			"NEW MADISON", "NEW PHILADELPHIA", "NEW STRAITSVILLE", "NEWARK",
			"NEWBURGH HEIGHTS", "NEWCOMERSTOWN", "NEWPORT NEWS",
			"NEWTON FALLS", "NILES", "NONE", "NORCROSS", "NORFOLK",
			"NORTH CANTON", "NORTH JACKSON", "NORTH LAWRENCE", "NORTH OLMSTED",
			"NORTH ROYALTON", "NORTHFIELD", "NORTON", "NORWALK", "NORWICH",
			"OAK HARBOR", "OCALA", "OLMSTED FALLS", "OREGON", "ORRVILLE",
			"OTTAWA", "OWASSO", "PACIFICA", "PAINESVILLE", "PALMDALE",
			"PANDORA", "PARKERSBURG", "PARMA", "PATASKALA", "PATRIOT",
			"PAULDING", "PEDRO", "PEMBERVILLE", "PENINSULA", "PENSACOLA",
			"PEPPER PIKE", "PERRYSBURG", "PHILO", "PHOENIX", "PICKERINGTON",
			"PIKETON", "PIQUA", "PITTSBURGH", "PLAIN CITY", "PLEASANT CITY",
			"PLEASANT PLAIN", "POMEROY", "POMPANO", "POMPANO BEACH", "PONTIAC",
			"PORT ST LUCIE", "PORTLAND", "PORTSMOUTH", "POTTSTOWN",
			"POWHATAN POINT", "QUAKER CITY", "QUINCY", "RAPID RIVER",
			"RAVENNA", "REYNOLDSBURG", "RICHMOND", "RICHWOOD", "RITTMAN",
			"ROCHESTER", "ROCKBRIDGE", "ROGERS", "ROOTSTOWN", "ROSEVILLE",
			"ROSEVILLE, PERRY CO.", "ROSSVILLE", "ROSWELL", "RUSHVILLE",
			"S ZANESVILLE", "S. ZANESVILLE", "SABINA", "SAINT CLAIRSVILLE",
			"SAINT JAMES", "SALEM", "SALESVILLE", "SALINEVILLE", "SANDUSKY",
			"SANTA ANA", "SARAHSVILLE", "SCIO", "SEAMAN", "SENECAVILLE",
			"SHADYSIDE", "SHAKER HEIGHTS", "SHAWNEE", "SHEFFIELD LAKE",
			"SHELBY", "SIDNEY", "SILVER SPRINGS", "SMITHVILLE",
			"SO. ZANESVILLE", "SOMERSET", "SONORA", "SOUTH BLOOMFIELD",
			"SOUTH POINT", "SOUTH ZANESVILLE", "SOUTHPORT", "SPRINGBORO",
			"SPRINGDALE", "SPRINGFIELD", "ST CLAIRSVLE", "ST LOUISVILLE",
			"ST PARIS", "ST PETERSBURG", "ST. CLAIRSVILLE", "STEUBENVILLE",
			"STEWART", "STOCKPORT", "STOUTSVILLE", "STOW", "SUGAR GROVE",
			"SUGER GROVE", "SUMMERSVILLE", "SUNBURY", "SWANTON", "SYLVANIA",
			"TALLMADGE", "TAYLOR", "TEMPE", "THORNVILLE", "TIFFIN", "TOLEDO",
			"TRENTON", "TRINWAY", "TROTWOOD", "TROY", "UHRICHSVILLE", "UNION",
			"UNIONTOWN", "UNIVERSITY HEIGHTS", "UNKNOWN", "UPPER ARLINGTON",
			"UPPER SANDUSKY", "URBANA", "UTICA", "VAN WERT", "VANDALIA",
			"VIRGINIA BEACH", "W LAFAYETTE", "WALHONDING", "WALNUT HILLS",
			"WAPAKONETA", "WARREN", "WARSAW", "WASHINGTON COURT HOUSE",
			"WAUKESHA", "WAUSEON", "WAVERLY", "WAYNESFIELD", "WELLSTON",
			"WELLSVILLE", "WEST CHESTER", "WEST JEFFERSON", "WEST LAFAYETTE",
			"WEST LIBERTY", "WEST UNION", "WESTERVILLE", "WESTLAKE",
			"WESTLAND", "WHEELING", "WHIPPLE", "WHITE COTTAGE", "WHITEHALL",
			"WHITING", "WICKLIFFE", "WILLIAMSFIELD", "WILLIAMSPORT",
			"WILMINGTON", "WINCHESTER", "WOODSFIELD", "WOOSTER", "WORTHINGTON",
			"XENIA", "YELLOW SPRINGS", "YORK", "YOUNGSTOWN", "ZANESVILLE",
			"ZANESVILLE,", "ZANESVILLEO" };

	private static String[] businesses = { "FURNISHINGS", "BAKERY",
			"ACCOUNTING", "TEXTILES", "MANUFACTURING", "INDUSTRIES",
			"PRO SERVICES", "LANDSCAPING", "REALTY", "TRAVEL",
			"MEDICAL SUPPLIES", "OFFICE SUPPLIES", "INSURANCE", "SOFTWARE",
			"MOTORS", "CAFE", "SERVICES", "GYMNASIUM", "MOTOR SERVICES" };

	private static String getRandomName(String[] names, int chance) {
		if (random.nextInt(100) < chance) {
			return names[random.nextInt(names.length)];
		}
		return null;
	}

	private static String getRandomName(String[] names) {
		return getRandomName(names, 100);
	}

	public static String getFirstName() {
		return getRandomName(firstNames);
	}

	public static String getFirstName(int chance) {
		return getRandomName(firstNames, chance);
	}

	public static String getLastName() {
		return getRandomName(lastNames);
	}

	public static String getStreetName() {
		return getRandomName(streetNames);
	}

	public static String getStreetSuffix() {
		return getRandomName(addressSuffixes);
	}

	public static String getCity() {
		return getRandomName(cities);
	}

	public static String getAddress() {
		int num = 103 + random.nextInt(1400);
		return num + " " + getStreetName() + " " + getStreetSuffix();
	}

	public static Date getBirthDate() {
		Date base = new Date(0);
		return getDate(base, -365 * 15, 365 * 15);
	}

	public static int getNumber() {
		return getNumber(Integer.MIN_VALUE, Integer.MAX_VALUE);
	}

	public static int getNumber(int max) {
		return getNumber(0, max);
	}

	public static int getNumber(int min, int max) {
		return min + random.nextInt(max - min);
	}

	public static Date getDate(int year, int month, int day) {
		Calendar cal = Calendar.getInstance();
		cal.clear();
		cal.set(year, month - 1, day, 0, 0, 0);
		return cal.getTime();
	}

	public static Date getDate(Date baseDate, int minDaysFromDate,
			int maxDaysFromDate) {
		Calendar cal = Calendar.getInstance();
		cal.setTime(baseDate);
		int diff = minDaysFromDate
				+ (random.nextInt(maxDaysFromDate - minDaysFromDate));
		cal.add(Calendar.DATE, diff);
		return cal.getTime();
	}

	public static Date getDate(Date minDate, Date maxDate) {
		int seconds = (int) ((maxDate.getTime() - minDate.getTime()) / 1000);
		seconds = random.nextInt(seconds);
		Date result = new Date();
		result.setTime(minDate.getTime() + (seconds * 1000));
		return result;
	}

	public static String getRandomText(int maxLength) {
		return getRandomText(maxLength, maxLength >> 1);
	}

	public static String getRandomText(int maxLength, int minLength) {
		String res = "";
		while (res.length() < minLength) {
			res = res + generateWord() + " ";
		}
		while (res.length() < maxLength) {
			res = res + generateWord() + " ";
		}
		// in case we spilled over
		if (res.length() > maxLength) {
			res = res.substring(0, maxLength - 1);
		}
		return res.trim();
	}

	public static char getRandomChar() {
		return (char) (random.nextInt(2) + 'a');
	}

	public static String generateWord() {
		return generateWord(1, 10);
	}

	public static String generateWord(int minLen, int maxLen) {
		int len = maxLen - minLen;
		if (len < 0) {
			len = 10;
			minLen = 1;
		}

		len = minLen + random.nextInt(len);

		StringBuilder sb = new StringBuilder(len);
		for (int i = 0; i < len; i++) {
			sb.append(getRandomChar());
		}
		return sb.toString();
	}

	public static String getSuffix(int chance) {
		return getRandomName(suffixes, chance);
	}

	public static String getPrefix(int chance) {
		return getRandomName(prefixes, chance);
	}

	public static String getNumberText(int digits) {
		String result = "";
		for (int i = 0; i < digits; i++) {
			result = result + random.nextInt(10);
		}
		return result;
	}

	public static String getBusinessName() {
		return getCity() + " " + getRandomName(businesses);
	}	
}
