/*
 * Copyright 2010, Andrew M Gibson
 *
 * www.andygibson.net
 *
 * This file is part of Spigot.
 *
 * Spigot is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * Spigot is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * 
 * You should have received a copy of the GNU General Public License
 * along with Spigot.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

package org.fluttercode.spigot.testing;

import java.util.Calendar;
import java.util.Date;
import java.util.Random;

/**
 * Class that provides a number of methods for generating test data.
 * 
 * @author Andy Gibson
 * 
 */
/**
 * @author GIBSOA01
 *
 */
/**
 * @author GIBSOA01
 *
 */
/**
 * @author GIBSOA01
 * 
 */
public final class TestDataFactory {

	private static Random random = new Random();

	private static String[] suffixes = { "II", "III", "Phd", "Jr", "Sr" };
	private static String[] prefixes = { "Mr", "Mrs", "Ms" };
	private static String[] firstNames = { "AARON", "ABBY", "ABIGAIL", "ADAM",
			"ALAN", "ALBERT", "ALEX", "ALEXANDRA", "ALEXIS", "ALICE", "ALICIA",
			"ALISHA", "ALISSA", "ALLEN", "ALLISON", "ALYSSA", "AMANDA",
			"AMBER", "AMY", "ANDREA", "ANDREW", "ANDY", "ANGEL", "ANGELA",
			"ANGIE", "ANITA", "ANN", "ANNA", "ANNETTE", "ANTHONY", "ANTONIO",
			"APRIL", "ARTHUR", "ASHLEY", "AUDREY", "AUSTIN", "AUTUMN", "BABY",
			"BARB", "BARBARA", "BECKY", "BENJAMIN", "BETH", "BETHANY", "BETTY",
			"BEVERLY", "BILL", "BILLIE", "BILLY", "BLAKE", "BOB", "BOBBIE",
			"BOBBY", "BONNIE", "BRAD", "BRADLEY", "BRADY", "BRANDI", "BRANDON",
			"BRANDY", "BREANNA", "BRENDA", "BRENT", "BRETT", "BRIAN",
			"BRIANNA", "BRITTANY", "BROOKE", "BROOKLYN", "BRUCE", "BRYAN",
			"CALEB", "CAMERON", "CANDY", "CARL", "CARLA", "CARMEN", "CAROL",
			"CAROLYN", "CARRIE", "CASEY", "CASSANDRA", "CATHERINE", "CATHY",
			"CHAD", "CHARLENE", "CHARLES", "CHARLIE", "CHARLOTTE", "CHASE",
			"CHASITY", "CHASTITY", "CHELSEA", "CHERYL", "CHESTER", "CHEYENNE",
			"CHRIS", "CHRISTIAN", "CHRISTINA", "CHRISTINE", "CHRISTOPH",
			"CHRISTOPHER", "CHRISTY", "CHUCK", "CINDY", "CLARA", "CLARENCE",
			"CLAYTON", "CLIFFORD", "CLINT", "CODY", "COLTON", "CONNIE",
			"COREY", "CORY", "COURTNEY", "CRAIG", "CRYSTAL", "CURTIS",
			"CYNTHIA", "DAKOTA", "DALE", "DALLAS", "DALTON", "DAN", "DANA",
			"DANIEL", "DANIELLE", "DANNY", "DARLA", "DARLENE", "DARRELL",
			"DARREN", "DAVE", "DAVID", "DAWN", "DEAN", "DEANNA", "DEBBIE",
			"DEBORAH", "DEBRA", "DENISE", "DENNIS", "DEREK", "DERRICK",
			"DESTINY", "DEVIN", "DIANA", "DIANE", "DILLON", "DIXIE", "DOMINIC",
			"DON", "DONALD", "DONNA", "DONNIE", "DORIS", "DOROTHY", "DOUG",
			"DOUGLAS", "DREW", "DUANE", "DUSTIN", "DUSTY", "DYLAN", "EARL",
			"ED", "EDDIE", "EDWARD", "ELAINE", "ELIZABETH", "ELLEN", "EMILY",
			"ERIC", "ERICA", "ERIKA", "ERIN", "ERNEST", "ETHAN", "EUGENE",
			"EVA", "EVELYN", "EVERETT", "FAITH", "FATHER", "FELICIA", "FLOYD",
			"FRANCIS", "FRANK", "FRED", "GABRIEL", "GAGE", "GAIL", "GARY",
			"GENE", "GEORGE", "GERALD", "GINA", "GINGER", "GLEN", "GLENN",
			"GLORIA", "GRACE", "GREG", "GREGORY", "HALEY", "HANNAH", "HARLEY",
			"HAROLD", "HARRY", "HEATH", "HEATHER", "HEIDI", "HELEN", "HERBERT",
			"HOLLY", "HOPE", "HOWARD", "HUNTER", "IAN", "ISAAC", "JACK",
			"JACKIE", "JACOB", "JADE", "JAKE", "JAMES", "JAMIE", "JAN", "JANE",
			"JANET", "JANICE", "JARED", "JASMINE", "JASON", "JAY", "JEAN",
			"JEANNIE", "JEFF", "JEFFERY", "JEFFREY", "JENNA", "JENNIFER",
			"JENNY", "JEREMIAH", "JEREMY", "JERRY", "JESSE", "JESSICA",
			"JESSIE", "JILL", "JIM", "JIMMY", "JOANN", "JOANNE", "JODI",
			"JODY", "JOE", "JOEL", "JOEY", "JOHN", "JOHNATHAN", "JOHNNY",
			"JON", "JONATHAN", "JONATHON", "JORDAN", "JOSEPH", "JOSH",
			"JOSHUA", "JOYCE", "JUANITA", "JUDY", "JULIA", "JULIE", "JUSTIN",
			"KAITLYN", "KAREN", "KATELYN", "KATHERINE", "KATHLEEN", "KATHRYN",
			"KATHY", "KATIE", "KATRINA", "KAY", "KAYLA", "KAYLEE", "KEITH",
			"KELLY", "KELSEY", "KEN", "KENDRA", "KENNETH", "KENNY", "KEVIN",
			"KIM", "KIMBERLY", "KRIS", "KRISTA", "KRISTEN", "KRISTIN",
			"KRISTINA", "KRISTY", "KYLE", "KYLIE", "LACEY", "LAKEN", "LANCE",
			"LARRY", "LAURA", "LAWRENCE", "LEAH", "LEE", "LEONARD", "LEROY",
			"LESLIE", "LEVI", "LEWIS", "LINDA", "LINDSAY", "LINDSEY", "LISA",
			"LLOYD", "LOGAN", "LOIS", "LORETTA", "LORI", "LOUIS", "LYNN",
			"MADISON", "MANDY", "MARCUS", "MARGARET", "MARIA", "MARIAH",
			"MARIE", "MARILYN", "MARION", "MARK", "MARLENE", "MARSHA",
			"MARTHA", "MARTIN", "MARTY", "MARVIN", "MARY", "MARY ANN", "MASON",
			"MATT", "MATTHEW", "MAX", "MEGAN", "MELANIE", "MELINDA", "MELISSA",
			"MELODY", "MICHAEL", "MICHELLE", "MICKEY", "MIKE", "MINDY",
			"MIRANDA", "MISTY", "MITCHELL", "MOLLY", "MONICA", "MORGAN",
			"MOTHER", "MYRON", "NANCY", "NATASHA", "NATHAN", "NICHOLAS",
			"NICK", "NICOLE", "NINA", "NOAH", "NORMA", "NORMAN", "OLIVIA",
			"PAIGE", "PAM", "PAMELA", "PAT", "PATRICIA", "PATRICK", "PATTY",
			"PAUL", "PAULA", "PEGGY", "PENNY", "PETE", "PHILLIP", "PHYLLIS",
			"RACHAEL", "RACHEL", "RALPH", "RANDALL", "RANDI", "RANDY", "RAY",
			"RAYMOND", "REBECCA", "REGINA", "RENEE", "REX", "RHONDA",
			"RICHARD", "RICK", "RICKY", "RITA", "ROB", "ROBBIE", "ROBERT",
			"ROBERTA", "ROBIN", "ROCHELLE", "ROCKY", "ROD", "RODNEY", "ROGER",
			"RON", "RONALD", "RONDA", "RONNIE", "ROSE", "ROXANNE", "ROY",
			"RUSS", "RUSSELL", "RUSTY", "RUTH", "RYAN", "SABRINA", "SALLY",
			"SAM", "SAMANTHA", "SAMUEL", "SANDRA", "SANDY", "SARA", "SARAH",
			"SAVANNAH", "SCOTT", "SEAN", "SETH", "SHANDA", "SHANE", "SHANNA",
			"SHANNON", "SHARON", "SHAUN", "SHAWN", "SHAWNA", "SHEILA",
			"SHELLY", "SHER", "SHERRI", "SHERRY", "SHIRLEY", "SIERRA",
			"SKYLER", "STACEY", "STACY", "STANLEY", "STEPHANIE", "STEPHEN",
			"STEVE", "STEVEN", "SUE", "SUMMER", "SUSAN", "SYDNEY", "TABATHA",
			"TABITHA", "TAMARA", "TAMMY", "TARA", "TASHA", "TASHIA", "TAYLOR",
			"TED", "TERESA", "TERRI", "TERRY", "TESSA", "THELMA", "THERESA",
			"THOMAS", "TIA", "TIFFANY", "TIM", "TIMMY", "TIMOTHY", "TINA",
			"TODD", "TOM", "TOMMY", "TONI", "TONY", "TONYA", "TRACEY",
			"TRACIE", "TRACY", "TRAVIS", "TRENT", "TREVOR", "TREY", "TRISHA",
			"TRISTAN", "TROY", "TYLER", "TYRONE", "UNBORN", "VALERIE",
			"VANESSA", "VERNON", "VERONICA", "VICKI", "VICKIE", "VICKY",
			"VICTOR", "VICTORIA", "VINCENT", "VIRGINIA", "VIVIAN", "WALTER",
			"WANDA", "WAYNE", "WENDY", "WESLEY", "WHITNEY", "WILLIAM", "xxxx",
			"WILLIE", "WYATT", "ZACHARY"

	};

	private static String[] lastNames = { "ABBOTT", "ACEVEDO", "ACOSTA",
			"ADAMS", "ADKINS", "AGUILAR", "AGUIRRE", "ALBERT", "ALEXANDER",
			"ALFORD", "ALLEN", "ALLISON", "ALSTON", "ALVARADO", "ALVAREZ",
			"ANDERSON", "ANDREWS", "ANTHONY", "ARMSTRONG", "ARNOLD", "ASHLEY",
			"ATKINS", "ATKINSON", "AUSTIN", "AVERY", "AVILA", "AYALA", "AYERS",
			"BAILEY", "BAIRD", "BAKER", "BALDWIN", "BALL", "BALLARD", "BANKS",
			"BARBER", "SMITH", "JOHNSON", "WILLIAMS", "JONES", "BROWN",
			"DAVIS", "MILLER", "WILSON", "MOORE", "TAYLOR", "ANDERSON",
			"THOMAS", "JACKSON", "BARKER", "BARLOW", "BARNES", "BARNETT",
			"BARR", "BARRERA", "BARRETT", "BARRON", "BARRY", "BARTLETT",
			"BARTON", "BASS", "BATES", "BATTLE", "BAUER", "BAXTER", "BEACH",
			"BEAN", "BEARD", "BEASLEY", "BECK", "BECKER", "BELL", "BENDER",
			"BENJAMIN", "BENNETT", "BENSON", "BENTLEY", "BENTON", "BERG",
			"BERGER", "BERNARD", "BERRY", "BEST", "BIRD", "BISHOP", "BLACK",
			"BLACKBURN", "BLACKWELL", "BLAIR", "BLAKE", "BLANCHARD",
			"BLANKENSHIP", "BLEVINS", "BOLTON", "BOND", "BONNER", "BOOKER",
			"BOONE", "BOOTH", "BOWEN", "BOWERS", "BOWMAN", "BOYD", "BOYER",
			"BOYLE", "BRADFORD", "BRADLEY", "BRADSHAW", "BRADY", "BRANCH",
			"BRAY", "BRENNAN", "BREWER", "BRIDGES", "BRIGGS", "BRIGHT",
			"BRITT", "BROCK", "BROOKS", "BROWN", "BROWNING", "BRUCE", "BRYAN",
			"BRYANT", "BUCHANAN", "BUCK", "BUCKLEY", "BUCKNER", "BULLOCK",
			"BURCH", "BURGESS", "BURKE", "BURKS", "BURNETT", "BURNS", "BURRIS",
			"BURT", "BURTON", "BUSH", "BUTLER", "BYERS", "BYRD", "CABRERA",
			"CAIN", "CALDERON", "CALDWELL", "CALHOUN", "CALLAHAN", "CAMACHO",
			"CAMERON", "CAMPBELL", "CAMPOS", "CANNON", "CANTRELL", "CANTU",
			"CARDENAS", "CAREY", "CARLSON", "CARNEY", "CARPENTER", "CARR",
			"CARRILLO", "CARROLL", "CARSON", "CARTER", "CARVER", "CASE",
			"CASEY", "CASH", "CASTANEDA", "CASTILLO", "CASTRO", "CERVANTES",
			"CHAMBERS", "CHAN", "CHANDLER", "CHANEY", "CHANG", "CHAPMAN",
			"CHARLES", "CHASE", "CHAVEZ", "CHEN", "CHERRY", "CHRISTENSEN",
			"CHRISTIAN", "CHURCH", "CLARK", "CLARKE", "CLAY", "CLAYTON",
			"CLEMENTS", "CLEMONS", "CLEVELAND", "CLINE", "COBB", "COCHRAN",
			"COFFEY", "COHEN", "COLE", "COLEMAN", "COLLIER", "COLLINS",
			"COLON", "COMBS", "COMPTON", "CONLEY", "CONNER", "CONRAD",
			"CONTRERAS", "CONWAY", "COOK", "COOKE", "COOLEY", "COOPER",
			"COPELAND", "CORTEZ", "COTE", "COTTON", "COX", "CRAFT", "CRAIG",
			"CRANE", "CRAWFORD", "CROSBY", "CROSS", "CRUZ", "CUMMINGS",
			"CUNNINGHAM", "CURRY", "CURTIS", "DALE", "DALTON", "DANIEL",
			"DANIELS", "DAUGHERTY", "DAVENPORT", "DAVID", "DAVIDSON", "DAVIS",
			"DAWSON", "DAY", "DEAN", "DECKER", "DEJESUS", "DELACRUZ",
			"DELANEY", "DELEON", "DELGADO", "DENNIS", "DIAZ", "DICKERSON",
			"DICKINSON", "DILLARD", "DILLON", "DIXON", "DODSON", "DOMINGUEZ",
			"DONALDSON", "DONOVAN", "DORSEY", "DOTSON", "DOUGLAS", "DOWNS",
			"DOYLE", "DRAKE", "DUDLEY", "DUFFY", "DUKE", "DUNCAN", "DUNLAP",
			"DUNN", "DURAN", "DURHAM", "DYER", "EATON", "EDWARDS", "ELLIOTT",
			"ELLIS", "ELLISON", "EMERSON", "ENGLAND", "ENGLISH", "ERICKSON",
			"ESPINOZA", "ESTES", "ESTRADA", "EVANS", "EVERETT", "EWING",
			"FARLEY", "FARMER", "FARRELL", "FAULKNER", "FERGUSON", "FERNANDEZ",
			"FERRELL", "FIELDS", "FIGUEROA", "FINCH", "FINLEY", "FISCHER",
			"FISHER", "FITZGERALD", "FITZPATRICK", "FLEMING", "FLETCHER",
			"FLORES", "FLOWERS", "FLOYD", "FLYNN", "FOLEY", "FORBES", "FORD",
			"FOREMAN", "FOSTER", "FOWLER", "FOX", "FRANCIS", "FRANCO", "FRANK",
			"FRANKLIN", "FRANKS", "FRAZIER", "FREDERICK", "FREEMAN", "FRENCH",
			"FROST", "SMITH", "JOHNSON", "WILLIAMS", "JONES", "BROWN", "DAVIS",
			"MILLER", "WILSON", "MOORE", "TAYLOR", "FRY", "FRYE", "FUENTES",
			"FULLER", "FULTON", "GAINES", "GALLAGHER", "GALLEGOS", "GALLOWAY",
			"GAMBLE", "GARCIA", "GARDNER", "GARNER", "GARRETT", "GARRISON",
			"GARZA", "GATES", "GAY", "GENTRY", "GEORGE", "GIBBS", "GIBSON",
			"GILBERT", "GILES", "GILL", "GILLESPIE", "GILLIAM", "GILMORE",
			"GLASS", "GLENN", "GLOVER", "GOFF", "GOLDEN", "GOMEZ", "GONZALES",
			"GONZALEZ", "GOOD", "GOODMAN", "GOODWIN", "GORDON", "GOULD",
			"GRAHAM", "GRANT", "GRAVES", "GRAY", "GREEN", "GREENE", "GREER",
			"GREGORY", "GRIFFIN", "GRIFFITH", "GRIMES", "GROSS", "GUERRA",
			"GUERRERO", "GUTHRIE", "GUTIERREZ", "GUY", "GUZMAN", "HAHN",
			"HALE", "HALEY", "HALL", "HAMILTON", "HAMMOND", "HAMPTON",
			"HANCOCK", "HANEY", "HANSEN", "HANSON", "HARDIN", "HARDING",
			"HARDY", "HARMON", "HARPER", "HARRIS", "HARRINGTON", "HARRIS",
			"HARRISON", "HART", "HARTMAN", "HARVEY", "HATFIELD", "HAWKINS",
			"HAYDEN", "HAYES", "HAYNES", "HAYS", "HEAD", "HEATH", "HEBERT",
			"HENDERSON", "HENDRICKS", "HENDRIX", "HENRY", "HENSLEY", "HENSON",
			"HERMAN", "HERNANDEZ", "HERRERA", "HERRING", "HESS", "HESTER",
			"HEWITT", "HICKMAN", "HICKS", "HIGGINS", "HILL", "HINES", "HINTON",
			"HOBBS", "HODGE", "HODGES", "HOFFMAN", "HOGAN", "HOLCOMB",
			"HOLDEN", "HOLDER", "HOLLAND", "HOLLOWAY", "HOLMAN", "HOLMES",
			"HOLT", "HOOD", "HOOPER", "HOOVER", "HOPKINS", "HOPPER", "HORN",
			"HORNE", "HORTON", "HOUSE", "HOUSTON", "HOWARD", "HOWE", "HOWELL",
			"HUBBARD", "HUBER", "HUDSON", "HUFF", "HUFFMAN", "HUGHES", "HULL",
			"HUMPHREY", "HUNT", "HUNTER", "HURLEY", "HURST", "HUTCHINSON",
			"HYDE", "INGRAM", "IRWIN", "JACKSON", "JACOBS", "JACOBSON",
			"JAMES", "JARVIS", "JEFFERSON", "JENKINS", "JENNINGS", "JENSEN",
			"JIMENEZ", "JOHNS", "JOHNSON", "JOHNSTON", "JONES", "JORDAN",
			"JOSEPH", "JOYCE", "JOYNER", "JUAREZ", "JUSTICE", "KANE",
			"KAUFMAN", "KEITH", "KELLER", "KELLEY", "KELLY", "KEMP", "KENNEDY",
			"KENT", "KERR", "KEY", "KIDD", "KIM", "KING", "KINNEY", "KIRBY",
			"KIRK", "KIRKLAND", "KLEIN", "KLINE", "KNAPP", "KNIGHT", "KNOWLES",
			"KNOX", "KOCH", "KRAMER", "LAMB", "LAMBERT", "LANCASTER", "LANDRY",
			"LANE", "LANG", "LANGLEY", "LARA", "LARSEN", "LARSON", "LAWRENCE",
			"LAWSON", "LE", "LEACH", "LEBLANC", "LEE", "LEON", "LEONARD",
			"LESTER", "LEVINE", "LEVY", "LEWIS", "LINDSAY", "LINDSEY",
			"LITTLE", "LIVINGSTON", "LLOYD", "LOGAN", "LONG", "LOPEZ", "LOTT",
			"LOVE", "LOWE", "LOWERY", "LUCAS", "LUNA", "LYNCH", "LYNN",
			"LYONS", "MACDONALD", "MACIAS", "MACK", "MADDEN", "MADDOX",
			"MALDONADO", "MALONE", "MANN", "MANNING", "MARKS", "MARQUEZ",
			"MARSH", "MARSHALL", "MARTIN", "MARTINEZ", "MASON", "MASSEY",
			"MATHEWS", "MATHIS", "MATTHEWS", "MAXWELL", "MAY", "MAYER",
			"MAYNARD", "MAYO", "MAYS", "MCBRIDE", "MCCALL", "MCCARTHY",
			"MCCARTY", "MCCLAIN", "MCCLURE", "MCCONNELL", "MCCORMICK", "MCCOY",
			"MCCRAY", "MCCULLOUGH", "MCDANIEL", "MCDONALD", "MCDOWELL",
			"MCFADDEN", "MCFARLAND", "SMITH", "JOHNSON", "WILLIAMS", "JONES",
			"BROWN", "DAVIS", "MCGEE", "MCGOWAN", "MCGUIRE", "MCINTOSH",
			"MCINTYRE", "MCKAY", "MCKEE", "MCKENZIE", "MCKINNEY", "MCKNIGHT",
			"MCLAUGHLIN", "MCLEAN", "MCLEOD", "MCMAHON", "MCMILLAN", "MCNEIL",
			"MCPHERSON", "MEADOWS", "MEDINA", "MEJIA", "MELENDEZ", "MELTON",
			"MENDEZ", "MENDOZA", "MERCADO", "MERCER", "MERRILL", "MERRITT",
			"MEYER", "MEYERS", "MICHAEL", "MIDDLETON", "MILES", "MILLER",
			"MILLS", "MIRANDA", "MITCHELL", "MOLINA", "MONROE", "MONTGOMERY",
			"MONTOYA", "MOODY", "MOON", "MOONEY", "MOORE", "MORALES", "MORAN",
			"MORENO", "MORGAN", "MORIN", "MORRIS", "MORRISON", "MORROW",
			"MORSE", "MORTON", "MOSES", "MOSLEY", "MOSS", "MUELLER", "MULLEN",
			"MULLINS", "MUNOZ", "MURPHY", "MURRAY", "MYERS", "NASH", "NAVARRO",
			"NEAL", "NELSON", "NEWMAN", "NEWTON", "NGUYEN", "NICHOLS",
			"NICHOLSON", "NIELSEN", "NIEVES", "NIXON", "NOBLE", "NOEL",
			"NOLAN", "NORMAN", "NORRIS", "NORTON", "NUNEZ", "OBRIEN", "OCHOA",
			"OCONNOR", "ODOM", "ODONNELL", "OLIVER", "OLSEN", "OLSON", "ONEAL",
			"ONEIL", "ONEILL", "ORR", "ORTEGA", "ORTIZ", "OSBORN", "OSBORNE",
			"OWEN", "OWENS", "PACE", "PACHECO", "PADILLA", "PAGE", "PALMER",
			"PARK", "PARKER", "PARKS", "PARRISH", "PARSONS", "PATE", "PATEL",
			"PATRICK", "PATTERSON", "PATTON", "PAUL", "PAYNE", "PEARSON",
			"PECK", "PENA", "PENNINGTON", "PEREZ", "PERKINS", "PERRY",
			"PETERS", "PETERSEN", "PETERSON", "PETTY", "PHELPS", "PHILLIPS",
			"PICKETT", "PIERCE", "PITTMAN", "PITTS", "POLLARD", "POOLE",
			"POPE", "PORTER", "POTTER", "POTTS", "POWELL", "POWERS", "PRATT",
			"PRESTON", "PRICE", "PRINCE", "PRUITT", "PUCKETT", "PUGH", "QUINN",
			"RAMIREZ", "RAMOS", "RAMSEY", "RANDALL", "RANDOLPH", "RASMUSSEN",
			"RATLIFF", "RAY", "RAYMOND", "REED", "REESE", "REEVES", "REID",
			"REILLY", "REYES", "REYNOLDS", "RHODES", "RICE", "RICH", "RICHARD",
			"RICHARDS", "RICHARDSON", "RICHMOND", "RIDDLE", "RIGGS", "RILEY",
			"RIOS", "RIVAS", "RIVERA", "RIVERS", "ROACH", "ROBBINS",
			"ROBERSON", "ROBERTS", "ROBERTSON", "ROBINSON", "ROBLES", "ROCHA",
			"RODGERS", "RODRIGUEZ", "RODRIQUEZ", "ROGERS", "ROJAS", "ROLLINS",
			"ROMAN", "ROMERO", "ROSA", "ROSALES", "ROSARIO", "ROSE", "ROSS",
			"ROTH", "ROWE", "ROWLAND", "ROY", "RUIZ", "RUSH", "RUSSELL",
			"RUSSO", "RUTLEDGE", "RYAN", "SALAS", "SALAZAR", "SALINAS",
			"SAMPSON", "SANCHEZ", "SANDERS", "SANDOVAL", "SANFORD", "SANTANA",
			"SANTIAGO", "SANTOS", "SARGENT", "SAUNDERS", "SAVAGE", "SAWYER",
			"SCHMIDT", "SCHNEIDER", "SCHROEDER", "SCHULTZ", "SCHWARTZ",
			"SCOTT", "SEARS", "SELLERS", "SERRANO", "SEXTON", "SHAFFER",
			"SHANNON", "SHARP", "SHARPE", "SHAW", "SHELTON", "SHEPARD",
			"SHEPHERD", "SHEPPARD", "SHERMAN", "SHIELDS", "SHORT", "SILVA",
			"SIMMONS", "SIMON", "SIMPSON", "SIMS", "SINGLETON", "SKINNER",
			"SLATER", "SLOAN", "SMALL", "SMITH", "SNIDER", "SNOW", "SNYDER",
			"SOLIS", "SOLOMON", "SOSA", "SOTO", "SPARKS", "SPEARS", "SPENCE",
			"SPENCER", "STAFFORD", "STANLEY", "STANTON", "STARK", "STEELE",
			"STEIN", "STEPHENS", "SMITH", "JOHNSON", "WILLIAMS", "STEPHENSON",
			"STEVENS", "STEVENSON", "STEWART", "STOKES", "STONE", "STOUT",
			"STRICKLAND", "STRONG", "STUART", "SUAREZ", "SULLIVAN", "SUMMERS",
			"SUTTON", "SWANSON", "SWEENEY", "SWEET", "SYKES", "TALLEY",
			"TANNER", "TATE", "TAYLOR", "TERRELL", "TERRY", "THOMAS",
			"THOMPSON", "THORNTON", "TILLMAN", "TODD", "TORRES", "TOWNSEND",
			"TRAN", "TRAVIS", "TREVINO", "TRUJILLO", "TUCKER", "TURNER",
			"TYLER", "TYSON", "UNDERWOOD", "VALDEZ", "VALENCIA", "VALENTINE",
			"VALENZUELA", "VANCE", "VANG", "VARGAS", "VASQUEZ", "VAUGHAN",
			"VAUGHN", "VAZQUEZ", "VEGA", "VELASQUEZ", "VELAZQUEZ", "VELEZ",
			"VAN HALEN", "VINCENT", "VINSON", "WADE", "WAGNER", "WALKER",
			"WALL", "WALLACE", "WALLER", "WALLS", "WALSH", "WALTER", "WALTERS",
			"WALTON", "WARD", "WARE", "WARNER", "WARREN", "WASHINGTON",
			"WATERS", "WATKINS", "WATSON", "WATTS", "WEAVER", "WEBB", "WEBER",
			"WEBSTER", "WEEKS", "WEISS", "WELCH", "WELLS", "WEST", "WHEELER",
			"WHITAKER", "WHITE", "WHITEHEAD", "WHITFIELD", "WHITLEY",
			"WHITNEY", "WIGGINS", "WILCOX", "WILDER", "WILEY", "WILKERSON",
			"WILKINS", "WILKINSON", "WILLIAM", "WILLIAMS", "WILLIAMSON",
			"WILLIS", "WILSON", "WINTERS", "WISE", "WITT", "WOLF", "WOLFE",
			"WONG", "WOOD", "WOODARD", "WOODS", "WOODWARD", "WOOTEN",
			"WORKMAN", "WRIGHT", "WYATT", "WYNN", "YANG", "YATES", "YORK",
			"YOUNG", "ZAMORA", "ZIMMERMAN" };

	private static String[] streetNames = { "ABERDEEN", "ABINGTON", "ACADEMY",
			"ADAIR", "ADAMS", "ADAMSVILLE", "AERYVIEW", "AGINES", "AIRPORT",
			"AIRWOOD", "AKRON", "ALAMEDA", "ALBERT", "ALBRIGHT", "ALBURN",
			"ALEXIS", "ALFRED", "ALICE", "ALKIRE", "ALLEN", "ALLISON", "ALVIN",
			"AMBARASSDOR", "AMBER", "AMHURST", "AMSTERDAM", "ANTIGUA",
			"APPLEGATE", "ARBORWOOD", "ARCADIA", "ARCH", "ARCHER", "ARLINGTON",
			"ARMCO", "ARMSTRONG", "ARNOLD", "ARROWHEAD", "ARTHUR", "ASHBURTON",
			"ASHLEY", "ASPEN", "ATHENA", "ATHENS", "ATLANTIC", "AUBURN",
			"AUSTIN", "AVALON", "AVON", "AXLINE", "AYERS", "BABBS", "BACK",
			"BAGLEY", "BAILEY", "BAIRD", "BAKER", "BALL", "BALLARD", "BALLOV",
			"BANK", "BARDITH", "BARKEY", "BARKLEY", "BARNES", "BARR", "BASIL",
			"BASIN", "BATEMAN", "BAUGHMAN", "BEAM", "BEARD", "BEATTY",
			"BEAUTY", "BEECH", "BEECHCREEK", "BEECHMONT", "BEELINE", "BELDEN",
			"BELL", "BELLFLOWER", "BELLVIEW", "BELLWOOD", "BELMONT",
			"BENJAMIN", "BENNETT", "BENWOOD", "BERKLEY", "BEST", "BETHESDA",
			"BEULAH", "BEVERLY", "BEXLEY", "BILLINGSLEY", "BISSETT", "BISSON",
			"BLACK", "BLACKBURN", "BLACKRUN", "BLACKSTONE", "BLACKWOOD",
			"BLAINE", "BLALOCK", "BLANDY", "BLENNERHASSETT", "BLOCKSOM",
			"BLOOMFIELD", "BLOSSOM", "BLUE", "BLUFF", "BOBBY", "BODMANN",
			"BOGGS", "BOLEN", "BOLTON", "BONAPARTE", "BONIFIELD", "BONNAIR",
			"BONSELS", "BOSTON", "BOTTOM", "BOWMAN", "BOWSER", "BOWTOWN",
			"BRADINGTON", "BRANCH", "BRANDYWINE", "BREEZEWOOD", "BREWERS",
			"BRIARBUSH", "BRIARCLIFF", "BRIARLEIGH", "BRICK", "BRIDGE",
			"BRIGHTON", "BRILL", "BRISTOL", "BRITTON", "BROAD", "BROADVUE",
			"BROADWAY", "BROOKFIELD", "BROOKOVER", "BROOKSIDE", "BROWN",
			"BROWNS", "BRYAN", "BUCK", "BUCKEYE", "BUCKINGHAM", "BURBANK",
			"BURLINGTON", "BURNELL", "BURNET", "BURNS", "BUSCH", "BUTLER",
			"BUTTER", "BUTTERMILK", "BYRNE", "CALEB", "CALVERT", "CAMBON",
			"CAMBRIDGE", "CAMDEN", "CAMP", "CAMPBELL", "CANAL", "CANDLESTICK",
			"CANEWOOD", "CANFIELD", "CANNELVILLE", "CANNEVILLE", "CANNON",
			"CARBONDALE", "CAREY", "CARL", "CARLISLE", "CARLTON", "CARLYSLE",
			"CARMEN", "CAROL", "CARPENTER", "CARROLL", "CARSON", "CARVER",
			"CASS", "CASTON", "CASTOR", "CATALPA", "CATHY", "CATT", "CATTAIL",
			"CATTLE", "CECIL", "CEDAR", "CEDARHURST", "CELINA", "CEMENTARY",
			"CEMETERY", "CENTER", "CENTRAL", "CERAMIC", "CHALFANT",
			"CHANDLERSVILLE", "CHAPMAN", "CHARDON", "CHARLENE", "CHARLES",
			"CHASE", "CHATAUQUA", "CHATHAM", "CHENEY", "CHERLICK", "CHERRY",
			"CHESAPEAKE", "CHESTER", "CHESTERFIELD", "CHESTNUT", "CHEVINGTON",
			"CHEWELAH", "CHILDRENS", "CHILLICOTHE", "CHINA", "CHOCTAW",
			"CHRISTOPHER", "CHRISTY", "CHURCH", "CHURCHFIELD", "CIRCLE",
			"CIRCLEVILLE", "CLAIRBOURNE", "CLAIRE", "CLARENCE", "CLARENDON",
			"CLARICE", "CLARK", "CLARY", "CLAY", "CLAYSVILLE", "CLEARCREEK",
			"CLEAREY", "CLEARPORT", "CLEARVIEW", "CLEVE", "CLEVELAND",
			"CLEVENGER", "CLIFFROCK", "CLIFFWOOD", "CLINTON", "CLOVER",
			"CLOVERIDGE", "CLYDE", "COBURG", "COCHRAN", "CODELL", "COHEN",
			"COLBURN", "COLLEGE", "COLLINGWOOD", "COLLINS", "COLONY",
			"COLUMBIA", "COLUMBUS", "COMIN", "COMMISSIONER", "COMMONWEALTH",
			"CONN", "CONVERS", "COOPERMILL", "COOPERRIDERS", "COOPERWELL",
			"CORNELL", "CORNSTILL", "CORONADO", "CORVUS", "CORWIN", "COSGRAVE",
			"COSHOCTON", "COTTAGE", "COUNTISS", "COUNTRYSIDE", "COURT", "COVE",
			"COVENTRY", "COWDEN", "CRANFIELD", "CRAWFORD", "CREAMERY",
			"CREEDMOOR", "CREEKVIEW", "CRESTWAY", "CROCK", "CROOKS", "CROSIER",
			"CROSS", "CROSSGATE", "CROW", "CROWN", "CULBERTSON", "CURTIS",
			"DADS", "DAISY", "DALE", "DALLMAN", "DANA", "DANIELS", "DANVILLE",
			"DARCIE", "DARLA", "DARLINGTON", "DATE", "DAVIS", "DAWNLIGHT",
			"DAWSON", "DEARBORN", "DECEMBER", "DECROW", "DEER", "DEERFIELD",
			"DEERPATH", "DEEWOOD", "DELLWOOD", "DELMONT", "DELWOOD", "DENBIGH",
			"DENLINGER", "DENMARK", "DENNING", "DENNIS", "DENNY", "DEPOT",
			"DETROIT", "DEVIN", "DEVLIN", "DEWEY", "DIAGONAL", "DICKINSON",
			"DICKSON", "DIETZ", "DILLON", "DISCOVERY", "DIXIE", "DIXON",
			"DOGWOOD", "DONA", "DONALD", "DOOLEYS", "DOROTHY", "DORU",
			"DOUGLAS", "DOWLING", "DOWNARD", "DOWNING", "DRAGOO", "DRESDEN",
			"DRYDEN", "DUNDEE", "DUNHAM", "DUNZWEILER", "DURBAN", "DUVALL",
			"DYER", "EAST", "EASTER", "EASTERN", "EASTFIELD", "EASTLAWN",
			"EASTMAN", "EASTMOOR", "EASTPORT", "EASTVIEW", "EASTWARD",
			"EASTWOOD", "EATON", "ECHO", "EDALBERT", "EDDIE", "EDDY", "EDERER",
			"EDGEWATER", "EDISON", "EDNA", "EDWARD", "EDWARDS", "ELDWOOD",
			"ELFIN", "ELIDA", "ELIZABETH", "ELLEN", "ELLER", "ELLIS",
			"ELLSWORTH", "ELMVILLE", "EMILY", "ENGLEWOOD", "ENON", "EPPLEY",
			"ERIE", "ERIN", "ESSEX", "EUCLID", "EVANS", "EVANSPORT", "EVELYN",
			"EVERGREEN", "EWING", "EXCHANGE", "EXTENSION", "FAIR", "FAIRALL",
			"FAIRBANKS", "FAIRCREST", "FAIRMONT", "FAIRMOUNT", "FAIRVIEW",
			"FAIRWAY", "FALLSBURG", "FALT", "FARSON", "FAWN", "FAYE",
			"FAYETTE", "FEDERAL", "FERNCLIFF", "FERNSTONE", "FERRELL", "FESS",
			"FIELD", "FINDLEY", "FIRST", "FISHERS", "FITZGERALD", "FLEEK",
			"FLEMING", "FLINT", "FLINTRIDGE", "FLINTWOOD", "FLORENCE",
			"FOREST", "FORRY", "FOSTER", "FOUNDS", "FOUNTAIN", "FOWLERS",
			"FOXFIRE", "FRAME", "FRANCIS", "FRANKLIN", "FRAZEYSBURG",
			"FREEBORN", "FREEDOM", "FRICK", "FRIENDSHIP", "FRISCO", "FRITTER",
			"FRONT", "FRONTIER", "FULBROOK", "FULTON", "FULTONROSE",
			"GALBRAITH", "GALENA", "GALIGHER", "GALIGHNER", "GALLIA", "GALWAY",
			"GANT", "GANTZ", "GARDEN", "GARDENWAY", "GAREY", "GARFIELD",
			"GARNER", "GARRELL", "GARRETT", "GARST", "GASLIGHT", "GAYLA",
			"GENESSEE", "GEORGE", "GEST", "GIBBARD", "GIFFORD", "GILBERT",
			"GLADE", "GLENA", "GLENAVEN", "GLENDALE", "GLENHAVEN", "GLENN",
			"GLENWILLOW", "GLENWOOD", "GLESSNER", "GODDARD", "GOMBER",
			"GOOSECREEK", "GORDON", "GORRELL", "GORSUCH", "GOSLEN", "GRACE",
			"GRAFFIS", "GRAND", "GRANDVIEW", "GRANGER", "GRANT", "GRANVILLE",
			"GRATIOT-NEWARK", "GRAY", "GRAYLOCK", "GREEN", "GREENBRIAR",
			"GREENBRIER", "GREENGOLD", "GREENHOUSE", "GREENVILLE", "GREENWOOD",
			"GREINER", "GRIEVES", "GROVE", "GUAVA", "HAESSLER", "HALE", "HALL",
			"HAMBURG", "HAMILTON", "HAMLINE", "HAMPTON", "HANAWALT", "HANNAH",
			"HANNAWALT", "HANOVER", "HANSON", "HARBOR", "HARDESTY", "HARDING",
			"HARDY", "HARKERS", "HARLAN", "HARMON", "HARMONY", "HARPER",
			"HARRIS", "HARRISON", "HARSHMAN", "HARTFORD", "HARTMAN",
			"HARTVILLE", "HARTWELL", "HARVEY", "HAUGHT", "HAWK", "HAWKES",
			"HAYES", "HAZEL", "HAZLETT", "HEATH", "HEBER", "HEBRON", "HECKAK",
			"HECKEL", "HEDGEWOOD", "HELENE", "HELPAR", "HENDERSHOT", "HENRY",
			"HERITAGE", "HERRON", "HEWITT", "HICKAM", "HICKMAN", "HICKORY",
			"HICKS", "HIDEAWAY", "HIGGINS", "HIGH", "HIGHLAND", "HIGHVIEW",
			"HILBISH", "HILDRETH", "HILL", "HINMAN", "HOGANS", "HOGE",
			"HOILES", "HOLBEIN", "HOLBERT", "HOLLIDAY", "HOLMES", "HOME",
			"HOMELESS", "HOMER", "HOMES", "HOMESTEAD", "HOMEWOOD", "HOOVER",
			"HOPEWELL", "HOSPITAL", "HOWARD", "HOWELL", "HUDSON", "HUEY",
			"HUGHES", "HUMPHREY", "HUNT", "HUNTER", "HUNTERDON", "HUNTINGTON",
			"IDAHO", "IDLEWOOD", "ILDEWOOD", "ILIAMNA", "IMLAY",
			"INDEPENDENCE", "INDIANA", "INDIANOLA", "INWOOD", "IRELAND",
			"IRON", "ISLAND", "JACKSON", "JAMES", "JAMESTOWN", "JANNETT",
			"JEFFERSON", "JENKINS", "JENSEN", "JESSAMINE", "JEWETT", "JEWITT",
			"JODY", "JOHN", "JOHNSON", "JOHNSTOWN", "JONATHAN", "JONES",
			"JORDAN", "JOYCE", "JUANITA", "JULIAN", "JUNIPER", "KAHLER",
			"KATHERINE", "KAUFFMAN", "KEARNS", "KEEN", "KEGS", "KELLY",
			"KENNEDY", "KENNY", "KENSINGTON", "KENTON", "KERRI", "KETTERING",
			"KEVROB", "KEYSTONE", "KIBLER", "KIMES", "KING", "KINGS",
			"KINGSLEY", "KINGSWOOD", "KINSMAN", "KINZEL", "KIRK", "KLOTZ",
			"KNIPE", "KNOX", "KOPCHAK", "KOSSUCH", "LACON", "LAFAYETTE",
			"LAGONDA", "LAKE", "LAKESIDE", "LAKEWOOD", "LAMBERT", "LANCASTER",
			"LANCASTER-CHILLICOTH", "LANDER", "LANEWAY", "LANGAN", "LARK",
			"LARKSPUR", "LARRY", "LARZELERE", "LASALLE", "LASHLEY", "LAUREL",
			"LAVONA", "LAWHEAD", "LAWN", "LAWNDALE", "LAWSON", "LAWYERS",
			"LAYTON", "LAZELERE", "LECTRIC", "LEDBETTER", "LEEDOM", "LEFFLER",
			"LEFTER", "LEGION", "LENOX", "LENT", "LEON", "LEONARD",
			"LEONARDVILLE", "LESLIE", "LESSLAR", "LEWIS", "LEXINGTON",
			"LIBERTY", "LICKING", "LILLIAN", "LIMA", "LIMESTONE", "LINCOLN",
			"LINCOLNWAY", "LINDALE", "LINDBERGH", "LINDEN", "LINDSAY", "LINN",
			"LINWOOD", "LISA", "LITHOPOLIS", "LIVINGSTON", "LOCK", "LOCKSMITH",
			"LOCUST", "LODGE", "LOMITA", "LONDON", "LONG", "LOOKOUT", "LOST",
			"LOUDON", "LOUISE", "LOVERS", "LUBRING", "LUCAS", "LUCASBURG",
			"LUCK", "LUNDGREN", "LUTZ", "MACEDONIA", "MACKENZIE", "MADISON",
			"MAILEY", "MAIN", "MALIBU", "MANNING", "MANOR", "MANSFIELD",
			"MAPLE", "MAPLECRAFT", "MAPLEVIEW", "MAPLEWOOD", "MARCHMONT",
			"MARIETTA", "MARION", "MARK", "MARKET", "MARKETING", "MARLO",
			"MARNE", "MARSHA", "MARSHDALE", "MARTIN", "MARTINEL", "MARY",
			"MAST", "MATTHEWS", "MAYFAIR", "MAYSVILLE", "MCARTHUR", "MCCARLEY",
			"MCCASLIN", "MCCLAIN", "MCCLURE", "MCCONNELL", "MCCONNELLSVILLE",
			"MCDANIEL", "MCDONALD", "MCFARLAND", "MCINTIRE", "MCKAIG",
			"MCKEEVER", "MCKINLEY", "MCMILLAN", "MCOWENS", "MEAD", "MEADOW",
			"MEADOWBROOK", "MEADOWHAVEN", "MEADOWOOD", "MECHANICSBURG", "MEEK",
			"MELICK", "MELROSE", "MEMORY", "MERIDIAN", "MERIWETHER", "MERLIN",
			"MERRIAM", "MERRICK", "MERRIMAC", "MERRYHILL", "MERSHON",
			"MESSIMER", "METRO", "MIAMI", "MICHAEL", "MICHIGAN", "MIDDLE",
			"MIDDLEFORK", "MIDDLETON", "MIDWAY", "MILAGRA", "MILITARY", "MILL",
			"MILLER", "MILLERS", "MILTON", "MINER", "MISSOURI", "MITCHELL",
			"MOCCASIN", "MOCK", "MOHAWK", "MOLLYSROCK", "MONA", "MONROE",
			"MONTAGUE", "MONTGOMERY", "MOONLIGHT", "MOORE", "MOOREHEAD",
			"MOORES", "MOOREWOOD", "MORGAN", "MORGANTOWN", "MORGANVILLE",
			"MORNINGSTAR", "MORRISON", "MORSE", "MOUND", "MOXADARLA",
			"MOXAHALA", "MUIRWOOD", "MULBERRY", "MUNDY", "MUNSON", "MURRAY",
			"MUSKINGUM", "MUSSELMAN", "MYRTLE", "NANCY", "NARROWS", "NATIONAL",
			"NAVY", "NEAL", "NEIL", "NELSON", "NEPTUNE", "NEWARK", "NEWGATE",
			"NEWLON", "NEWMAN", "NEWPORT", "NICHALAS", "NOLAN", "NONE",
			"NOR-BIXBEY", "NORA", "NORFIELD", "NORMANDY", "NORRIS", "NORTH",
			"NORTHCREST", "NORTHLAND", "NORWICH", "NORWOOD", "NOTTINGHAM",
			"NOTTINGHAMSHIRE", "NUGENT", "OAKLAND", "OAKWOOD", "OBETZ",
			"ODELL", "OHIO", "OKEY", "OLIVE", "OLNEY", "ONTARIO", "OPERA",
			"ORANGE", "ORCHARD", "ORDERS", "ORTON", "OSAGE", "OSCEOLA",
			"OTTERBEIN", "OVERLOOK", "OWENS", "OXFORD", "PAINT", "PALAMINO",
			"PALLAS", "PALMER", "PALMERAWAY", "PALMWOOD", "PALOMINO",
			"PARAGON", "PARISH", "PARK", "PARKER", "PARKS", "PARKVIEW",
			"PARKWAY", "PARKWOOD", "PARLIAMENT", "PARRY", "PARTRIDGE", "PATCH",
			"PATRICIA", "PEACHBLOW", "PEAR", "PEARL", "PEMBROKE", "PENN",
			"PENNEY", "PENNISULA", "PENNSYLVANIA", "PENRICK", "PERDUE",
			"PERINE", "PERKINS", "PERRY", "PERRYTON", "PERSHING", "PETERS",
			"PETERSBURG", "PETERSON", "PFEIFER", "PFEIFFER", "PHILADELPHIA",
			"PHILLIPS", "PICKWICK", "PIERCE", "PIKE", "PINE", "PINECREST",
			"PINETOWN", "PINEVIEW", "PINEWOOD", "PINKERTON", "PINKLEY",
			"PIONEER", "PIPER", "PLAINFIELD", "PLANTATION", "PLAYFORD",
			"PLEASANT", "PLEASANTVIEW", "PLEASANTVILLE", "POINTE", "POPLAR",
			"PORTAGE", "PORTER", "PORTLAND", "POTTERS", "POTTS", "POWELL",
			"PRAME", "PRATT", "PRICE", "PRINCETON", "PRIOR", "PRISON",
			"PROMWAY", "PROSPECT", "PRYOR", "PUBLIC", "PURDY", "PURVIS",
			"PUTNAM", "QUARRY", "QUICK", "QUINCY", "QUINLAN", "RACE", "RADNOR",
			"RAIDERS", "RAILROAD", "RAINS", "RAINTREE", "RANGE", "RANKIN",
			"RANSBOTTOM", "RAVEN", "RAVENWOOD", "RAWSON", "READING", "REAM",
			"REDMAN", "REDONDO", "REED", "REEVES", "REHL", "RESTLESS",
			"REYNOLDS", "RHONDA", "RICE", "RICHARDS", "RICHEY", "RICHMAN",
			"RICHMOND", "RICHVALE", "RICHWOOD", "RIDER", "RIDGE", "RIDGEFIELD",
			"RIDGELAND", "RIDGEVIEW", "RIDGEWOOD", "RIGBY", "RIGGIN", "RIGNY",
			"RITCHEY", "RITENOUR", "RIVER", "RIVERSIDE", "RIVERVIEW",
			"ROADAYLE", "ROBERTSON", "ROBIN", "ROBINSON", "ROBINWOOD", "ROCK",
			"ROCKVILLE", "ROEMER", "ROLAND", "ROLLINS", "RONDAYLE",
			"ROOSEVELT", "ROPER", "ROSE", "ROSEVILLE", "ROSEWOOD", "ROWLAND",
			"ROYALTON", "ROYMA", "RUCKER", "RUNYAN", "RUSSELL", "RUSTLE",
			"RUTH", "RYAN", "SALEM", "SALGARBER", "SALLY", "SALTZGABER",
			"SAMPSON", "SAMUEL", "SAND", "SANDHURST", "SANDRA", "SANDUSKY",
			"SANDVIK", "SANTOY", "SARAH", "SCARBOROUGH", "SCENIC", "SCHAUM",
			"SCHNEIDER", "SCHOLL", "SCHOOL", "SCHULER", "SCHULTZ", "SCHWALLIE",
			"SCOTT", "SCOUT", "SEALOVER", "SEAMAN", "SEBORN", "SELLS",
			"SELSAM", "SENATOR", "SEROCO", "SEVALL", "SEVERT", "SEWARD",
			"SEYMORE", "SHADY", "SHAGBARK", "SHALIMAN", "SHANDON", "SHARON",
			"SHARONWOOD", "SHASTA", "SHAW", "SHAWNEE", "SHEANDOAH", "SHEILA",
			"SHELLHART", "SHENANDOAH", "SHEPHERD", "SHERBORNE", "SHERIDAN",
			"SHERMAN", "SHERWOOD", "SHINDERN", "SHINICK", "SHINNICK",
			"SHIPLETT", "SHOOP", "SHORE", "SHORT", "SHUMAKER", "SIBLEY",
			"SILLIMAN", "SILMORE", "SKYLINE", "SKYVIEW", "SLACK", "SMITHFIELD",
			"SMITHWOOD", "SNOKE", "SNYDER", "SOFIN", "SOLIDA", "SOMERS",
			"SOMERSET", "SONORA", "SOUDER", "SOUTH", "SOUTHARD", "SOUTHEAST",
			"SOUTHERN", "SOUTHWARD", "SPANGLER", "SPARLING", "SPELLMAN",
			"SPENCE", "SPENCER", "SPIELBUSCH", "SPRATT", "SPRING",
			"SPRINGDALE", "SPRUCE", "SPRY", "STACY", "STALDER", "STALLING",
			"STANLEY", "STANSBERRY", "STANTON", "STANWAY", "STATE", "STEELE",
			"STEIN", "STEPHENS", "STEVENS", "STEVY", "STEWART", "STIERS",
			"STILLMEADOW", "STILLWELL", "STINE", "STIVER", "STOKELY", "STONE",
			"STONECREEK", "STORMONT", "STOUT", "STOUTSVILLE", "STRAWBERRY",
			"STREET", "STURTZ", "STYGLER", "SUDBURY", "SUGARGROVE",
			"SUGARTREE", "SUMMIT", "SUNDALE", "SUNFLOWER", "SUNKEL", "SUNRAY",
			"SUNRISE", "SUNSET", "SUPERIOR", "SURGER", "SWANS", "SWARTZ",
			"SWINGLE", "SYCAMORE", "TALFORD", "TALLEY", "TAMARRON", "TAMMY",
			"TANNEHILL", "TARKMAN", "TAYLOR", "TEAKWOOD", "TEDRICK", "TEMPLE",
			"TERRACE", "TERRY", "THEOBALD", "THIRD", "THOMAS", "THOMPSON",
			"THORN", "THORNBERRY", "THORNHILL", "THURMAN", "TIFFANY",
			"TILESTON", "TITUS", "TODD", "TONI", "TOWERS", "TOWN", "TRABUE",
			"TRACI", "TRACO", "TRANQUILITY", "TREEHOUSE", "TREMONT", "TREND",
			"TRIDELPHIA", "TUPEDO", "TURNER", "TURTLE", "TUSCARAWAS",
			"TWIMENHILL", "TYMAN", "UNDERWOOD", "UNEEDA", "UNION", "UNKNOWN",
			"VALLEY", "VANCE", "VAUGHN", "VENTURE", "VENUS", "VERNON",
			"VETTER", "VICKI", "VICTORY", "VILLA", "VILLAGE", "VINE", "VINSEL",
			"VIRGINIA", "VISTA", "VROOM", "WABASH", "WACKER", "WAKATOMIKA",
			"WALDOLF", "WALKER", "WALL", "WALLWORK", "WALNUT", "WALTER",
			"WALTHAM", "WARD", "WARGO", "WARNER", "WARNERS", "WARREN",
			"WARWICK", "WASHINGTON", "WATER", "WATERS", "WATKINS", "WATSON",
			"WATTS", "WAYNE", "WEAVER", "WEBB", "WEBSTER", "WEDGEWOOD",
			"WEEDON", "WELLER", "WELLS", "WENTZ", "WESSEX", "WEST",
			"WESTBOURNE", "WESTERN", "WESTMOOR", "WESTMORE", "WESTWOOD",
			"WETSELL", "WHALEY", "WHEATLAND", "WHEELABOUT", "WHEELER",
			"WHEELING", "WHIPPLE", "WHITES", "WHITMAN", "WILHELM", "WILKINS",
			"WILLIAMS", "WILLIS", "WILLOW", "WILMER", "WILMINGTON", "WILSHIRE",
			"WILSON", "WINDING", "WINDMILL", "WINDSONG", "WINFIELD",
			"WINLWOOD", "WINTER", "WINTON", "WISE", "WISTERIA", "WOGAN",
			"WOLFE", "WOLFORD", "WOODBERRY", "WOODBROOK", "WOODLAND",
			"WOODLAWN", "WOOLPER", "WORKMAN", "WORTMAN", "WREXHAM", "YALE",
			"YINGLING", "YOST", "YOUNG", "ZANE", "ZANESVILLE", "ZELLA" };

	private static String[] addressSuffixes = { "AVE", "BLVD", "CIR", "CRES",
			"CT", "DR", "HTS", "HWY", "LN", "PARK", "PATH", "PIKE", "PKWY",
			"PL", "RD", "RDG", "RUN", "SQ", "ST", "STA", "TER", "TRL", "WAY" };

	private static String[] cities = { "ABBA", "ABBEVILLE", "ACWORTH",
			"ADAIRSVILLE", "ADEL", "ADRIAN", "AILEY", "ALAMO", "ALAPAHA",
			"ALBANY", "ALLENHURST", "ALMA", "ALMA", "ALPHARETTA", "ALSTON",
			"AMBOY", "AMBROSE", "AMERICUS", "APPLING", "ARLINGTON", "ASHBURN",
			"ATHENS", "ATHENS-CLARKE COUNTY", "ATKINSON", "ATLANTA",
			"ATTAPULGUS", "AUBURN", "AUGUSTA", "AUGUSTA-RICHMOND COUNTY",
			"AUSTELL", "AVONDALE ESTATES", "AXSON", "BACONTON", "BADEN",
			"BAINBRIDGE", "BAINBRIDGE", "BALDWIN", "BANNOCKBURN",
			"BARNESVILLE", "BARNEY", "BARRETTS", "BARWICK", "BAXLEY", "BEMISS",
			"BERKELEY LAKE", "BERLIN", "BLACKSHEAR", "BLAIRSVILLE", "BLAKELY",
			"BLOOMINGDALE", "BLUE RIDGE", "BOGART", "BOSTON", "BOWDON",
			"BOWENS MILL", "BOWMAN", "BRASELTON", "BREMEN", "BRINSON",
			"BRISTOL", "BRONWOOD", "BROOKFIELD", "BROOKLET", "BROOKS",
			"BROXTON", "BRUNSWICK", "BUCHANAN", "BUENA VISTA", "BUFORD",
			"BUSHNELL", "BYROMVILLE", "BYRON", "CAIRO", "CAMILLA", "CANTON",
			"CARNESVILLE", "CARROLLTON", "CARTERSVILLE", "CAVE SPRING",
			"CECIL", "CEDARTOWN", "CENTERVILLE", "CHAMBLEE", "CHATSWORTH",
			"CHAUNCEY", "CHESTER", "CHICKAMAUGA", "CHULA", "CITY OF CALHOUN",
			"CITY OF SUMMERVILLE", "CLARKESVILLE", "CLARKSTON", "CLAXTON",
			"CLAYTON", "CLEVELAND", "CLYATTEVILLE", "CLYO", "COBBTOWN",
			"COCHRAN", "COGDELL", "COHUTTA", "COLESBURG", "COLLEGE PARK",
			"COLLINS", "COLQUITT", "COLUMBUS", "COMMERCE", "CONYERS",
			"COOLIDGE", "CORDELE", "CORNELIA", "COUNCIL",
			"COUNTRY CLUB ESTATE", "COVERDALE", "COVINGTON", "COX",
			"CRAWFORDVILLE", "CRESCENT", "CULLODEN", "CUMMING", "CUSSETA",
			"CUTHBERT", "DACULA", "DAHLONEGA", "DAISY", "DAKOTA", "DALLAS",
			"DALTON", "DAMASCUS", "DANIELSVILLE", "DARIEN", "DASHER", "DAWSON",
			"DAWSONVILLE", "DECATUR", "DENMARK", "DILLARD", "DIXIE",
			"DOCK JUNCTION", "DOERUN", "DONALSONVILLE", "DORAVILLE", "DOUGLAS",
			"DOUGLASVILLE", "DOVER BLUFF", "DUPONT", "DUBLIN", "DUDLEY",
			"DULUTH", "DUNWOODY", "EAST DUBLIN", "EAST POINT", "EASTMAN",
			"EATONTON", "EBENEZER", "EDISON", "EDITH", "EGYPT", "ELBERTON",
			"ELDORADO", "ELLABELLE", "ELLAVILLE", "ELLENTON", "ELLIJAY",
			"ENIGMA", "EUHARLEE", "EULONIA", "EVERITT", "FAIRBURN", "FAIRMONT",
			"FARGO", "FAYETTEVILLE", "FITZGERALD", "FLEMINGTON",
			"FLOWERY BRANCH", "FOLKSTON", "FOREST PARK", "FORSYTH",
			"FORT GAINES", "FORT OGLETHORPE", "FORT STEWART", "FORT VALLEY",
			"FRANKLIN", "FRUITLAND", "FUNSTON", "GAINESVILLE", "GARDEN CITY",
			"GARFIELD", "GENEVA", "GEORGETOWN", "GIBSON", "GLENNVILLE",
			"GLENWOOD", "GLORY", "GRAHAM", "GRAY", "GREENSBORO", "GREENVILLE",
			"GRIFFIN", "GROOVERVILLE", "GROVELAND", "GROVETOWN", "GUMBRANCH",
			"GUYTON", "HAGAN", "HAHIRA", "HAMILTON", "HAMPTON", "HAPEVILLE",
			"HARDING", "HARDING", "HARDWICKE", "HARRIETTS BLUFF", "HARTWELL",
			"HAWKINSVILLE", "HAYLON", "HAZLEHURST", "HELENA", "HEPZIBAH",
			"HIAWASSEE", "HICKOX", "HIGGSTON", "HINESVILLE", "HIRAM",
			"HOBOKEN", "HOGANSVILLE", "HOLLY SPRINGS", "HOLT", "HOMELAND",
			"HOMER", "HOMERVILLE", "HOPEULIKIT", "HORTENSE", "HOWELL", "INAHA",
			"IRON CITY", "IRWINTON", "IRWINVILLE", "ISLE OF HOPE-DUTCH ISLAND",
			"JACKSON", "JANIS", "JASPER", "JEFFERSON", "JEFFERSONVILLE",
			"JESUP", "JOHNS CREEK", "JONESBORO", "KELLER", "KENNESAW",
			"KINDERLOU", "KINGS BAY BASE", "KINGSLAND", "KIRKLAND", "KITE",
			"LAFAYETTE", "LAGRANGE", "LAKE CITY", "LAKE PARK", "LAKELAND",
			"LANIER", "LAWRENCEVILLE", "LAX", "LEARY", "LEEFIELD", "LEESBURG",
			"LENOX", "LEXINGTON", "LILBURN", "LINCOLNTON", "LITHONIA",
			"LOCUST GROVE", "LOGANVILLE", "LOOKOUT MOUNTAIN", "LOUISVILLE",
			"LOVEJOY", "LUDOWICI", "LULATON", "LUMBER CITY", "LUMPKIN",
			"LYONS", "MACON", "MADISON", "MANASSAS", "MANCHESTER", "MARIETTA",
			"MAXEYS", "MAYDAY", "MCDONOUGH", "MCINTOSH", "MCINTYRE", "MCRAE",
			"MEIGS", "MELDRIM", "MERSHON", "METTER", "MIDWAY", "MILAN",
			"MILLEDGEVILLE", "MILLEN", "MILTON", "MONIAC", "MONROE",
			"MONTEZUMA", "MONTGOMERY", "MONTICELLO", "MONTROSE", "MORA",
			"MORGAN", "MORROW", "MORVEN", "MOULTRIE", "MOUNT VERNON",
			"MOUNT ZION", "MOUNTAIN PARK", "MYSTIC", "NAHUNTA", "NANKIN",
			"NASHVILLE", "NEEDMORE", "NELSON", "NEVILS", "NEW ROCK HILL",
			"NEWNAN", "NEWTON", "NICHOLLS", "NORCROSS", "NORMAN PARK",
			"OAKWOOD", "OCHLOCKNEE", "OCILLA", "ODUM", "OFFERMAN", "OFFERMAN",
			"OGLETHORPE", "OMEGA", "OSTERFIELD", "OUSLEY", "OXFORD",
			"PALMETTO", "PARROTT", "PATTERSON", "PEACHTREE CITY WEBSITE",
			"PEARSON", "PELHAM", "PEMBROKE", "PERRY", "PHILLIPSBURG",
			"PINE LAKE", "PINEORA", "PINEVIEW", "POOLER", "PORT WENTWORTH",
			"PORTAL", "POTTER", "POULAN", "POWDER SPRINGS", "PRESTON",
			"PRIDGEN", "PULASKI", "QUEENSLAND", "QUITMAN", "RACE POND",
			"RAY CITY", "REBECCA", "REGISTER", "REIDSVILLE", "REMERTON",
			"RENTZ", "RETREAT", "RICEBORO", "RICHMOND HILL", "RIDGEVILLE",
			"RINCON", "RINGGOLD", "RIVERDALE", "RIVERSIDE", "ROCHELLE",
			"ROCKINGHAM", "ROCKMART", "ROME", "ROSWELL", "ROYSTON", "RUTLEDGE",
			"SAINT GEORGE", "SALE CITY", "SANDERSVILLE", "SANDY SPRINGS",
			"SASSER", "SAVANNAH", "SCREVEN", "SENOIA", "SESSOMS", "SHAWNEE",
			"SHELLMAN BLUFF", "SIRMANS", "SKIDAWAY ISLAND", "SMITHVILLE",
			"SMYRNA", "SNELLVILLE", "SOCIAL CIRCLE", "SOPERTON",
			"SOUTH NEWPORT", "SPARKS", "SPARTA", "SPRINGFIELD", "ST. MARYS",
			"ST. SIMONS ISLAND", "STATENVILLE", "STATESBORO", "STERLING",
			"STILLMORE", "STILLWELL", "STILSON", "STOCKBRIDGE", "STOCKTON",
			"STONE MOUNTAIN", "SUGAR HILL", "SUMNER", "SUNBURY", "SUNSWEET",
			"SURRENCY", "SUWANEE", "SWAINSBORO", "SYCAMORE", "SYLVANIA",
			"SYLVESTER", "TALBOTTON", "TALLAPOOSA", "TARBORO", "TARVER",
			"TEMPLE", "THALMAN", "THELMA", "THOMASTON", "THOMASVILLE",
			"THOMSON", "THUNDERBOLT", "TIFTON", "TOCCOA", "TOOMSBORO",
			"TOWNSEND", "TRENTON", "TRUDIE", "TUCKER", "TWIN CITY",
			"TWIN LAKES", "TY TY", "TYBEE ISLAND", "TYRONE", "UNADILLA",
			"UNION CITY", "UNIONVILLE", "UPTON", "UVALDA", "VALDOSTA",
			"VALONA", "VERNONBURG", "VIDALIA", "VIENNA", "VILLA RICA",
			"WALTHOURVILLE", "WARNER ROBINS", "WARRENTON", "WARWICK",
			"WASHINGTON", "WATERLOO", "WATKINSVILLE", "WAVERLY", "WAYCROSS",
			"WAYNESBORO", "WAYNESVILLE", "WEBER", "WEST GREEN", "WEST POINT",
			"WESTWOOD", "WHIGHAM", "WHITE OAK", "WHITMARSH ISLAND",
			"WILLACOOCHEE", "WILMINGTON ISLAND", "WINDER", "WINOKUR",
			"WITHERS", "WOODBINE", "WOODSTOCK", "WORTH", "WRAY", "WRIGHTSVILLE" };

	private static String[] businesses = { "FURNISHINGS", "BAKERY",
			"ACCOUNTING", "TEXTILES", "MANUFACTURING", "INDUSTRIES",
			"PRO SERVICES", "LANDSCAPING", "REALTY", "TRAVEL",
			"MEDICAL SUPPLIES", "OFFICE SUPPLIES", "INSURANCE", "SOFTWARE",
			"MOTORS", "CAFE", "SERVICES", "GYMNASIUM", "MOTOR SERVICES" };

	private static String[] words = { "throw", "ball", "hat", "red", "worn",
			"list", "words", "computer", "in", "out", "hot", "cold", "warp",
			"speed", "captain", "assert", "hold", "room", "ship", "lost", "is",
			"television", "show", "about", "plane", "crash", "island",
			"monster", "trees", "banging", "smoke", "where", "are", "we",
			"was", "asked", "no", "rescue", "came", "build", "fire", "waited",
			"days", "moved", "to", "caves", "found", "with", "ghost", "dad",
			"in", "white", "rabbit", "lock", "discovered", "hatch", "with",
			"boon", "secretly", "hid", "it", "while", "trying", "to", "open",
			"it", "until", "sidekick", "died", "as", "sacrifice", "island",
			"demanded", "many", "had", "dreams", "or", "visions", "others",
			"came", "took", "people", "who", "are", "they", "what", "do",
			"they", "want", "light", "came", "on", "through", "window",
			"leader", "is", "a", "good", "man", "numbers", "in", "room",
			"enter", "keys", "computer", "end", "of", "world", "wicket",
			"magnetic", "pull", "shepherd", "always", "wrong", "much",
			"suspense", "what", "to", "do", "when", "it", "ends", "I", "will",
			"have", "to", "find", "something", "else", "to", "pique", "my",
			"interest", "or maybe", "write", "lots", "of", "code", "probably",
			"should", "have", "generated", "this", "text", "automatically",
			"so", "will", "from", "the", "web" };

	private static String getRandomString(String[] values, int chance) {
		if (random.nextInt(100) < chance) {
			return values[random.nextInt(values.length)];
		}
		return null;
	}

	private static String getRandomString(String[] values) {
		return values[random.nextInt(values.length)];
	}

	/**
	 * @return A random first name
	 */
	public static String getFirstName() {
		return getRandomString(firstNames);
	}

	/**
	 * @return A random last name
	 */
	public static String getLastName() {
		return getRandomString(lastNames);
	}

	/**
	 * @return A random street name
	 */
	public static String getStreetName() {
		return getRandomString(streetNames);
	}

	/**
	 * @return A random street suffix
	 */
	public static String getStreetSuffix() {
		return getRandomString(addressSuffixes);
	}

	/**
	 * Generates a random city value
	 * 
	 * @return City as a string
	 */
	public static String getCity() {
		return getRandomString(cities);
	}

	/**
	 * Generates an address value
	 * 
	 * @return Address as a string
	 */
	public static String getAddress() {
		int num = 103 + random.nextInt(1400);
		return num + " " + getStreetName() + " " + getStreetSuffix();
	}

	/**
	 * Creates a random birthdate within the range of 1955 to 1985
	 * 
	 * @return Date representing a birthdate
	 */
	public static Date getBirthDate() {
		Date base = new Date(0);
		return getDate(base, -365 * 15, 365 * 15);
	}

	/**
	 * Returns a random int value.
	 * 
	 * @return random number
	 */
	public static int getNumber() {
		return getNumber(Integer.MIN_VALUE, Integer.MAX_VALUE);
	}

	/**
	 * Returns a random number between 0 and max
	 * 
	 * @param max
	 *            Maximum value of result
	 * @return random number no more than max
	 */
	public static int getNumber(int max) {
		return getNumber(0, max);
	}

	/**
	 * Returns a number betwen min and max
	 * 
	 * @param min
	 *            minimum value of result
	 * @param max
	 *            maximum value of result
	 * @return Random number within range
	 */
	public static int getNumber(int min, int max) {
		return min + random.nextInt(max - min);
	}

	/**
	 * Builds a date from the year, month, day values passed in
	 * 
	 * @param year
	 *            The year of the final {@link Date} result
	 * @param month
	 *            The month of the final {@link Date} result
	 * @param day
	 *            The day of the final {@link Date} result
	 * @return Date representing the passed in values.
	 */
	public static Date getDate(int year, int month, int day) {
		Calendar cal = Calendar.getInstance();
		cal.clear();
		cal.set(year, month - 1, day, 0, 0, 0);
		return cal.getTime();
	}

	/**
	 * Returns a random date which is in the range <code>baseData</code> +
	 * <code>minDaysFromData</code> to <code>baseData</code> +
	 * <code>maxDaysFromData</code>.
	 * 
	 * @param baseDate
	 *            Date to start from
	 * @param minDaysFromDate
	 *            minimum number of days from the baseDate the result can be
	 * @param maxDaysFromDate
	 *            maximum number of days from the baseDate the result can be
	 * @return A random date
	 */
	public static Date getDate(Date baseDate, int minDaysFromDate,
			int maxDaysFromDate) {
		Calendar cal = Calendar.getInstance();
		cal.setTime(baseDate);
		int diff = minDaysFromDate
				+ (random.nextInt(maxDaysFromDate - minDaysFromDate));
		cal.add(Calendar.DATE, diff);
		return cal.getTime();
	}

	/**
	 * Returns a random date between two dates
	 * 
	 * @param minDate
	 *            Minimum date that can be returned
	 * @param maxDate
	 *            Maximum date that can be returned
	 * @return random date between these two dates.
	 */
	public static Date getDate(Date minDate, Date maxDate) {
		int seconds = (int) ((maxDate.getTime() - minDate.getTime()) / 1000);
		seconds = random.nextInt(seconds);
		Date result = new Date();
		result.setTime(minDate.getTime() + (seconds * 1000));
		return result;
	}

	/**
	 * Returns a random string of characters of limited length.
	 * 
	 * @param maxLength
	 *            the maximum number of characters in the result
	 * @return a string of random characters
	 */
	public static String getRandomText(int maxLength) {
		return getRandomText(maxLength, maxLength >> 1);
	}

	/**
	 * Returns random text
	 * 
	 * @param maxLength
	 * @param minLength
	 * @return
	 */
	public static String getRandomText(int maxLength, int minLength) {
		String res = "";
		while (res.length() < minLength) {
			res = res + generateWord() + " ";
		}
		String result = res;
		int count = (maxLength - minLength) >> 3;
		while (res.length() < maxLength && count > 0) {
			result = res;
			res = res + generateWord() + " ";
			count--;
		}
		return result.trim();
	}

	/**
	 * @return a random character
	 */
	public static char getRandomChar() {
		return (char) (random.nextInt(26) + 'a');
	}

	/**
	 * Returns a word of a length between 1 and 10 characters.
	 * 
	 * @return A work of max length 10
	 */
	public static String generateWord() {
		return getRandomString(words);
	}

	/**
	 * Generate a random word of length between min and max length. If max-min
	 * len < 0 then a string of length 10 is returned.
	 * 
	 * @param minLen
	 *            minimum length of word
	 * @param maxLen
	 *            maximum length of word
	 * @return random word
	 */
	public static String generateWord(int minLen, int maxLen) {
		int len = maxLen - minLen;
		if (len < 0) {
			len = 10;
			minLen = 1;
		}

		len = minLen + random.nextInt(len);

		StringBuilder sb = new StringBuilder(len);
		for (int i = 0; i < len; i++) {
			sb.append(getRandomChar());
		}
		return sb.toString();
	}

	/**
	 * 
	 * @param chance
	 *            Chance of a suffix being returned
	 * @return
	 */
	public static String getSuffix(int chance) {
		return getRandomString(suffixes, chance);
	}

	/**
	 * Return a person prefix or null if the odds are too low.
	 * 
	 * @param chance
	 *            Odds of a prefix being returned
	 * @return Prefix string
	 */
	public static String getPrefix(int chance) {
		return getRandomString(prefixes, chance);
	}

	/**
	 * Returns a string containing a set of numbers with a fixed number of
	 * digits
	 * 
	 * @param digits
	 *            number of digits in the final number
	 * @return Random number as a string with a fixed length
	 */
	public static String getNumberText(int digits) {
		String result = "";
		for (int i = 0; i < digits; i++) {
			result = result + random.nextInt(10);
		}
		return result;
	}

	/**
	 * Generates a random business name by taking a city name and additing a
	 * business onto it.
	 * 
	 * @return A random business name
	 */
	public static String getBusinessName() {
		return getCity() + " " + getRandomString(businesses);
	}
}
